"""Phase 6: knowledge graph (memory/relationships.jsonl + 15_KNOWLEDGE_GRAPH.md).

Edges come from three places, each tagged with `basis`:
- EXPLICIT: a reference written in the source (e.g. "Status: reversed (D07, D09)");
- OVERLAY: curated edge with cited evidence (curated.EXTRA_EDGES, transitions, patterns);
- COMPUTED: mechanical (belief -> associated decision, record -> time period).
"""
from __future__ import annotations

import re
from collections import Counter

import curated as C
from common import write_jsonl, write_text

PERIODS = [  # from 13_KNOWLEDGE_GRAPH.md "Strategic evolution"
    ("period:phase0", "Phase 0: JARVIS v0", None, "2026-06-27"),
    ("period:phase1", "Phase 1: honest brain, headless", "2026-06-28", "2026-06-29"),
    ("period:phase2", "Phase 2: faces + private service", "2026-06-30", "2026-07-16"),
    ("period:phase3", "Phase 3: depth and speaks-first", "2026-07-17", "2026-07-30"),
    ("period:phase4", "Phase 4: agent-facing brain, measurement era", "2026-07-31", "2026-08-28"),
    ("period:current", "Current: launch, distribution, survival", "2026-08-29", "2026-09-10"),
]


def period_of(d):
    if not d or not re.match(r"\d{4}-\d\d-\d\d", d):
        return None
    for pid, _, a, b in PERIODS:
        if (a is None or d >= a) and d <= b:
            return pid
    return None


def build(model: dict) -> dict:
    P = C.PROJECT
    R = model["records"]
    edges = []

    def e(src, rel, dst, basis, note=""):
        edges.append({"id": f"E{len(edges) + 1:04d}", "from": src, "rel": rel, "to": dst, "basis": basis, "note": note})

    # explicit: decision text referencing other decisions
    for r in model["by_kind"].get("decisions", []):
        status = r["fields"].get("status", "")
        for d in re.findall(r"\bD\d\d\b", status):
            if d != r["local_id"]:
                rel = "superseded_by" if "supersed" in status.lower() or "revers" in status.lower() else "related_to"
                e(r["id"], rel, f"{P}:{d}", "EXPLICIT", status)
    # explicit: contradictions mentioning D/B ids
    for r in model["by_kind"].get("contradictions", []):
        for ref in sorted(set(re.findall(r"\b([DB]\d\d)\b", r["text"]))):
            e(r["id"], "related_to", f"{P}:{ref}", "EXPLICIT")
    # computed: belief -> decisions
    for r in R.values():
        if r["type"] == "belief":
            for d in r.get("associated_decisions") or []:
                e(r["id"], "supported", d, "COMPUTED", "belief associated with decision")
    # overlay
    for a, rel, b in C.EXTRA_EDGES:
        e(a, rel, b, "OVERLAY")
    for t in C.TRANSITIONS:
        for ref in t["refs"]:
            e(f"global:{t['id']}", "derived_from", ref, "OVERLAY")
    for gb in C.HISTORICAL_BELIEFS:
        for ref in gb[5]:
            e(f"global:{gb[0]}", "derived_from", ref, "OVERLAY")
    for d in C.DECISION_PATTERNS:
        for ref in d["evidence"]:
            e(ref, "supported", f"global:{d['id']}", "OVERLAY")
    for rl in C.RECURRING_LESSONS:
        for f in rl["failures"]:
            e(f"{P}:{f}", "led_to", f"global:{rl['id']}", "OVERLAY")
    for g in C.GLOBAL_CONTRADICTIONS:
        for ref in g["refs"]:
            e(f"global:{g['id']}", "contradicted", ref, "OVERLAY")
    for o in C.GLOBAL_OPEN_LOOPS:
        for ref in o["refs"]:
            e(f"global:{o['id']}", "related_to", ref, "OVERLAY")
    for a, rel, b, basis, note, refs in C.PROJECT_RELATIONS:
        e(f"project:{a}", rel, f"project:{b}", basis, note)
    for a, b in C.INTEREST_EDGES:
        e(f"global:{a}", "related_to", f"global:{b}", "OVERLAY", "co-occurring interest")
    for name, role, projs in C.PEOPLE:
        for p in projs:
            e(f"person:{name}", "related_to", f"project:{p}", "EXPLICIT", role)
    for t in C.TECHNOLOGIES:
        e(f"tech:{t}", "related_to", f"project:{P}", "EXPLICIT")
    # computed: records -> time period
    for r in R.values():
        pid = period_of(r.get("date"))
        if pid and r["type"] in {"decision", "episode", "failure"}:
            e(r["id"], "related_to", pid, "COMPUTED", "dated within period")
    # project membership for source records
    for r in R.values():
        if r["id"].startswith(f"{P}:") and r["type"] in {"decision", "belief", "failure", "open_loop"}:
            e(r["id"], "related_to", f"project:{P}", "COMPUTED", "extracted from project")

    write_jsonl("memory/relationships.jsonl", edges)
    model["edges"] = edges

    # ---- markdown
    rel_counts = Counter(x["rel"] for x in edges)
    basis_counts = Counter(x["basis"] for x in edges)
    title = lambda gid: _label(model, gid)
    lines = ["# 15 — Global Knowledge Graph", "",
             f"Generated by `compiler/build_graph.py`. {len(edges)} edges in `memory/relationships.jsonl`.",
             "Every edge has a `basis`: EXPLICIT (written in the source), OVERLAY (curated, with cited evidence), "
             "COMPUTED (mechanical). No causal edge is COMPUTED.", "",
             "| relation | count |", "|---|---|"] + [f"| {k} | {v} |" for k, v in sorted(rel_counts.items())] + [
             "", "| basis | count |", "|---|---|"] + [f"| {k} | {v} |" for k, v in sorted(basis_counts.items())] + [
             "", "## Node types", "",
             "projects · decisions · beliefs (source + reconstructed historical) · belief transitions · lessons · failures · "
             "open loops · contradictions · interests · people · technologies · time periods", "",
             "## Spine (projects, periods, people)", "", "```text"]
    lines += [
        "project:jarvis-v0 ──influenced──> project:icarus   (EXPLICIT: D01, B01)",
        "project:icarus ──related_to──> project:job-search-2026-09   (INFERRED: concurrent, not causal)",
        "project:icarus ──related_to──> project:harshitha-barter   (EXPLICIT: D28)",
        "",
        "period:phase0 → phase1 → phase2 → phase3 → phase4 → current (2026-09-10) → [no evidence to 2026-10-03]",
        "",
        "person:Alankrit ──builds through──> Claude Code (builder/auditor) + Codex (reviewer)",
        "```", "", "## Causal and reversal edges (EXPLICIT + OVERLAY only)", "", "```text"]
    causal = [x for x in edges if x["rel"] in {"led_to", "caused", "reversed", "superseded_by", "contradicted", "influenced"}
              and x["basis"] != "COMPUTED"]
    for x in causal:
        lines.append(f"{x['from']} ──{x['rel']}──> {x['to']}    # {title(x['from'])[:60]} → {title(x['to'])[:60]}")
    lines += ["```", "", "## Belief ↔ decision support (COMPUTED from overlay associations)", "", "```text"]
    for x in edges:
        if x["rel"] == "supported" and x["basis"] == "COMPUTED":
            lines.append(f"{x['from']} ──supported──> {x['to']}")
    lines += ["```", "", "## Interest graph", "", "```text"]
    for a, b in C.INTEREST_EDGES:
        lines.append(f"{title('global:' + a)} ──related_to── {title('global:' + b)}")
    lines += ["```", "", "Query the full graph: `memory/relationships.jsonl` (one JSON edge per line)."]
    write_text("15_KNOWLEDGE_GRAPH.md", "\n".join(lines) + "\n")
    return model


def _label(model, gid):
    r = model["records"].get(gid)
    if not r:
        return gid
    for k in ("title", "statement", "topic", "pattern", "lesson", "question", "q", "name", "event", "text", "a"):
        if r.get(k):
            return re.sub(r"[*`]", "", str(r[k]))
    return gid
