"""Curated reconciliation overlay: the judgment layer of the compiler.

Everything here is a compiler judgment over parsed source records. Rules:
- every entry cites source refs as "<project>:<local_id>" (validated by validate.py);
- statuses use the global vocabulary (CURRENT, PERSISTENT, EVOLVING, HISTORICAL,
  REJECTED, EXPLORATORY, UNCERTAIN);
- nothing here may introduce a fact absent from the source corpus. Where the
  overlay states an interpretation, it is marked basis="INFERRED".

When a new project extraction is added, extend this file rather than editing
the source corpus.
"""

PROJECT = "icarus"

# ------------------------------------------------------------------ projects
PROJECTS = [
    {
        "id": "jarvis-v0", "name": "JARVIS Engineering Intelligence v0",
        "period": "before 2026-06-27 (start date UNKNOWN)", "extracted": False,
        "evidence_level": "INDIRECT (described inside the Icarus extraction only)",
        "purpose": "Local, read-only Python CLI answering 'why was this decision made' over a local Git checkout.",
        "goals": ["Answer 'why' questions over a repo without bluffing", "Serve 5-20 engineer companies (ICP)"],
        "decisions": ["icarus:D01"], "pivots": ["Reset to docs-only and renamed Icarus on 2026-06-27 (deeper reason UNKNOWN)"],
        "technologies": ["Python", "local Git checkout", "inspector.py / evidence.py / isolation.py", "benchmarks"],
        "lessons": ["UNKNOWN: no v0 lessons recorded; v0 judged 'of no value' to the new direction"],
        "trajectory": "Origin of the thesis. 'Cannot bluff' and the voice + overlay scene already existed here.",
        "unresolved": ["Why the reset happened beyond 'new direction'", "When v0 started"],
        "status": "ARCHIVED (git tag jarvis-v0)", "refs": ["icarus:T01", "icarus:D01", "icarus:B01"],
    },
    {
        "id": "icarus", "name": "Icarus (engineering / organizational memory)",
        "period": "2026-06-27 to at least 2026-09-10 (resume claims founder role from 2026-03; UNVERIFIED)",
        "extracted": True, "evidence_level": "DIRECT (full extraction, 16 artifacts)",
        "purpose": "GitHub-backed engineering memory that answers why code is the way it is, with citations, or says 'no one wrote this down'.",
        "goals": ["Sellable engineering-memory company", "50 users (from 2026-09-04)",
                  "Maximum visibility for Icarus and Alankrit personally (from 2026-09-08)"],
        "decisions": [f"icarus:D{i:02d}" for i in range(1, 36)],
        "pivots": ["Brain-first headless build (06-28)", "Faces + hosted private service (Jul)",
                   "Organizational-memory positioning (06-30)", "Agent-facing brain via MCP (08-04)",
                   "Agent Mode reframed for novice builders (08-29)", "Launch, distribution and survival mode (09)"],
        "technologies": ["Python stdlib", "fastembed + BM25 + RRF", "tree-sitter / ast", "Gemini (gemini-paid)",
                         "SwiftUI/AppKit", "Chrome MV3", "Next.js/React/three.js", "MCP", "Azure ACA", "GitLab CI",
                         "Vercel", "PostHog (server counts)"],
        "lessons": ["global:RL01", "global:RL02", "global:RL03", "global:RL04", "global:RL05", "global:RL06"],
        "trajectory": "The main body of evidence about Alankrit. Engineering core shipped; commercial traction not achieved by 2026-09-10.",
        "unresolved": ["icarus:O1", "icarus:O2", "icarus:O4", "icarus:O8", "icarus:O27"],
        "status": "ACTIVE as of 2026-09-10; state after that UNKNOWN", "refs": ["icarus:T02", "icarus:T46"],
    },
    {
        "id": "job-search-2026-09", "name": "Job search (SDR/BDR, DevTools roles)",
        "period": "by 2026-09-07 to at least 2026-09-10", "extracted": False,
        "evidence_level": "INDIRECT (outputs/resume inside the Icarus repo; a separate 'Job Application Context' directory exists but was not extracted)",
        "purpose": "Income / role search running in parallel with Icarus.",
        "goals": ["6 SDR/BDR applications submitted", "DevTools-tailored resume (2026-09-10)"],
        "decisions": [], "pivots": ["LinkedIn headline 'Open to Early-Stage Roles' changed to founder framing on 2026-09-04, then applications from 09-07"],
        "technologies": [], "lessons": [], "trajectory": "Signals that Icarus was not a funded full-time bet (INFERRED, MEDIUM).",
        "unresolved": ["icarus:O27"], "status": "UNKNOWN outcome", "refs": ["icarus:T43", "icarus:C9"],
    },
    {
        "id": "harshitha-barter", "name": "Meta-ads product for Harshitha (barter)",
        "period": "agreed 2026-08-26; outcome UNKNOWN", "extracted": False, "evidence_level": "INDIRECT (one decision entry)",
        "purpose": "Alankrit builds her meta-ads product; she markets Icarus.", "goals": ["Delivered = repos connected"],
        "decisions": ["icarus:D28"], "pivots": [], "technologies": [], "lessons": [],
        "trajectory": "A cash-free distribution attempt.", "unresolved": ["icarus:O12"], "status": "UNKNOWN",
        "refs": ["icarus:D28", "icarus:C21"],
    },
]

# Projects named in the corpus but with no extraction (mention-only).
MENTIONED_PROJECTS = [
    ("Signal", "macOS Gmail automation, 'private beta'", "icarus:FACT01L13"),
    ("Tempo", "screenshots to motion video", "icarus:FACT01L13"),
    ("Pantheon.ai", "OSS CLI: product-context folder to a cited 13-artifact packet", "icarus:FACT01L13"),
    ("GRRBaow (employment)", "AI & Automation Engineer, Oct 2025 to Mar 2026: Zoom-to-CRM pipeline, VC document automation", "icarus:FACT01L9"),
    ("Ideas2IT (employment)", "Agentic AI Engineer intern, Jul 2025 to Feb 2026: 20 automated workflows, RAG content tools", "icarus:FACT01L9"),
    ("Marketing Intelligence", "working directory named in manifest; deliberately out of scope", "icarus:MANIFEST"),
    ("Job Application Context", "working directory named in manifest; deliberately out of scope", "icarus:MANIFEST"),
    ("Solar Forecasting", "working directory named in manifest; deliberately out of scope", "icarus:MANIFEST"),
]

PROJECT_RELATIONS = [
    ("jarvis-v0", "influenced", "icarus", "EXPLICIT", "Icarus was reset from v0 and kept its 'cannot bluff' thesis and JARVIS scene.", ["icarus:D01", "icarus:B01", "icarus:T01"]),
    ("icarus", "derived_from", "jarvis-v0", "EXPLICIT", "Archive tag jarvis-v0; 'evolved from his earlier local CLI'.", ["icarus:D01"]),
    ("icarus", "related_to", "job-search-2026-09", "INFERRED", "Concurrent from 2026-09-07; no causal statement in the record. Cash pressure (Azure unaffordable) is co-located in time.", ["icarus:FACT01L32", "icarus:D33"]),
    ("icarus", "related_to", "harshitha-barter", "EXPLICIT", "Barter: build her product in exchange for Icarus marketing.", ["icarus:D28"]),
]

# ------------------------------------------------------------------ beliefs
# status, first_observed, last_observed, decisions, contradicting, class
B = lambda status, first, last, decisions, contra, cls, projects=("icarus",), note="": dict(
    status=status, first=first, last=last, decisions=decisions, contradicting=contra, cls=cls,
    projects=list(projects), note=note)

BELIEFS = {
    "B01": B("PERSISTENT", "before 2026-06-27 (JARVIS v0 VISION)", "2026-09-10", ["D02", "D07", "D13", "D27"], [], "STRATEGIC PRINCIPLE", ("jarvis-v0", "icarus"),
             "Only belief evidenced across two project generations."),
    "B02": B("CURRENT", "2026-07-18", "2026-08-10", ["D13"], ["Learned three separate times: knowing it did not prevent recurrence (L7)"], "TECHNICAL KNOWLEDGE"),
    "B03": B("CURRENT", "2026-07 (three-valued freshness state; exact date UNKNOWN)", "2026-09-05", ["D21"], ["His own retry script turned failed lookups into 0 the same day he logged the lesson"], "STRATEGIC PRINCIPLE",
             note="Applied in engineering (three-valued state) and in distribution ('a zero from an unchecked channel is not a result')."),
    "B04": B("CURRENT", "2026-06-28 (gate on day one)", "2026-09-10", ["D02", "D07", "D13", "D14", "D27"], [], "TECHNICAL KNOWLEDGE"),
    "B05": B("CURRENT", "2026-08 (PROTOCOL.md)", "2026-09-05", [], [], "STRATEGIC PRINCIPLE", note="Governs how he treats AI agents' self-reports, including Claude audits."),
    "B06": B("CURRENT", "2026-08 (PROTOCOL.md)", "2026-08-29", ["D26"], [], "STRATEGIC PRINCIPLE"),
    "B07": B("CURRENT", "2026-08-22", "2026-09-05", ["D26"], ["Resume claims not read back against source (C9)"], "STRATEGIC PRINCIPLE"),
    "B08": B("CURRENT", "2026-09-05", "2026-09-05", [], [], "STRATEGIC PRINCIPLE", note="Single recorded observation; durable status not yet shown."),
    "B09": B("CURRENT", "2026-06-30", "2026-08-29", ["D06", "D30"], ["Push never built (O26)"], "PRODUCT KNOWLEDGE", note="Believed but unacted for push."),
    "B10": B("CURRENT", "2026-06-30", "2026-08-21", ["D06"], [], "PRODUCT KNOWLEDGE"),
    "B11": B("CURRENT", "2026-08-29", "2026-09-05", ["D30", "D32"], [], "PRODUCT KNOWLEDGE"),
    "B12": B("CURRENT", "2026-08-07 (never auto-merge)", "2026-09-05", ["D17", "D30", "D32"], [], "PRODUCT KNOWLEDGE"),
    "B13": B("EXPLORATORY", "2026-08-29", "2026-08-29", ["D30"], ["Unmeasured against a best-possible CLAUDE.md (O4)", "Target user has moved repeatedly (C15)"], "PROJECT-SPECIFIC"),
    "B14": B("CURRENT", "2026-07-28", "2026-07-28", [], ["Caps and exclusions still exist (C22)"], "PROJECT-SPECIFIC", note="Aspiration, not achieved state."),
    "B15": B("CURRENT", "2026-06-28", "2026-07-13", ["D02", "D08", "D09"], [], "BUSINESS KNOWLEDGE"),
    "B16": B("EVOLVING", "2026-06-28", "2026-08-27", ["D08", "D12", "D29"], ["Website stack relaxed the rule (C10)"], "TECHNICAL KNOWLEDGE", note="Scoped to the brain since 2026-08-26/27."),
    "B17": B("CURRENT", "2026-07 (vacuous tests found)", "2026-09-10", [], [], "TECHNICAL KNOWLEDGE"),
    "B18": B("CURRENT", "2026-07-13", "2026-09-05", [], [], "TECHNICAL KNOWLEDGE"),
    "B19": B("CURRENT", "2026-07-18", "2026-08-27", ["D12", "D14"], [], "STRATEGIC PRINCIPLE"),
    "B20": B("CURRENT", "2026-06-28 (foundation docs)", "2026-09-10", [], ["HANDOFF.md and STRATEGY.md drifted (C3, C4)"], "PERSONAL PREFERENCE"),
    "B21": B("CURRENT", "2026-07-16 ('business phase begins')", "2026-09-10", ["D31"], ["Engineering kept winning time through August (C16)"], "PROJECT-SPECIFIC",
             note="A diagnosis of Icarus at a moment. Recurrence of distribution as a hard problem elsewhere is MEDIUM evidence only."),
    "B22": B("CURRENT", "2026-08-17", "2026-09-04", ["D23"], [], "BUSINESS KNOWLEDGE"),
    "B23": B("CURRENT", "2026-08 (three instances)", "2026-09-10", ["D19", "D23"], [], "BUSINESS KNOWLEDGE"),
    "B24": B("CURRENT", "2026-08-17", "2026-09-10", ["D22", "D35"], [], "STRATEGIC PRINCIPLE"),
    "B25": B("UNCERTAIN", "2026-08 (Ideas.md)", "2026-09-10", [], ["In tension with B26 (C7)"], "UNCERTAIN"),
    "B26": B("CURRENT", "2026-08-17", "2026-09-10", ["D22"], ["Decided against his own data: vulnerable posts performed best", "Tension with B25 (C7)"], "PERSONAL PREFERENCE",
             note="Public-surface rule only; explicitly inverted for investors (B27)."),
    "B27": B("CURRENT", "2026-08-24 (Antler pitch item)", "2026-09-10", [], ["Resume overclaims (C9)"], "STRATEGIC PRINCIPLE"),
    "B28": B("CURRENT", "2026-09-02", "2026-09-10", ["D31"], ["LinkedIn DM outreach adopted 2026-09-04 is itself push (global:GC05)"], "BUSINESS KNOWLEDGE"),
    "B29": B("CURRENT", "2026-08-17", "2026-09-10", ["D23", "D28"], [], "PROJECT-SPECIFIC"),
    "B30": B("EXPLORATORY", "2026-09-01", "2026-09-01", ["D31"], [], "BUSINESS KNOWLEDGE", note="n=10 warm DMs, one day."),
    "B31": B("EXPLORATORY", "2026-09-10", "2026-09-10", ["D33"], [], "PROJECT-SPECIFIC"),
    "B32": B("CURRENT", "2026-08 (X thesis)", "2026-09-10", [], [], "STRATEGIC PRINCIPLE"),
    "B33": B("EXPLORATORY", "2026-06-30 (VISION 'category, longer term')", "2026-09-10", [], [], "UNCERTAIN"),
    "B34": B("EXPLORATORY", "2026-08-11", "2026-08-25", ["D19", "D26"], ["Effect shrank from 4/4 to 1/4 on correct measurement"], "TECHNICAL KNOWLEDGE"),
    "B35": B("EXPLORATORY", "2026-09-08", "2026-09-08", [], [], "STRATEGIC PRINCIPLE", note="Newest public framing; one X thread."),
}

# Historical / rejected beliefs reconstructed from decisions and reversals.
HISTORICAL_BELIEFS = [
    ("GB01", "Free hosted models and public repos only are an adequate MVP.", "HISTORICAL", "2026-06-29", "2026-07-13", ["icarus:D04", "icarus:D09", "icarus:D11"], "Reversed: private code is 'the product'; one private-safe paid writer."),
    ("GB02", "Private repos can be removed from the tester build.", "HISTORICAL", "2026-07-14", "2026-07-16", ["icarus:D11", "icarus:C12"], "Restored two days later."),
    ("GB03", "Cold email to buyers can open the market.", "REJECTED", "~2026-07-30", "2026-09-04", ["icarus:F31", "icarus:D31", "icarus:O23"], "~104 sends, 0 verified positive; declared dead 2026-09-04."),
    ("GB04", "Launch platforms (Show HN, Product Hunt) can create the first audience.", "REJECTED", "2026-08-25", "2026-09-04", ["icarus:F33", "icarus:F34", "icarus:D31"], "1 point, 1 upvote; declared dead."),
    ("GB05", "Tool descriptions rewritten on observable events take unprompted calls from 0/11 to 4/4.", "REJECTED", "2026-08-11", "2026-08-25", ["icarus:D19", "icarus:D26", "icarus:F25"], "Retracted to 1 of 4 across independent sessions."),
    ("GB06", "Post-hoc lexical attribution can detect fabricated composition.", "REJECTED", "2026-08", "2026-08", ["icarus:F04"], "Measured anti-correlated with truth; module deleted."),
    ("GB07", "More leads is the missing variable.", "REJECTED", "2026-08", "2026-08-17", ["icarus:F38", "icarus:D23"], "Weekly YC prospect automation retired; outreach list-gated."),
    ("GB08", "User data is discarded after each request.", "REJECTED", "before 2026-08-27", "2026-09-05", ["icarus:C1"], "Found false by the 2026-09-05 audit; vault still states it."),
    ("GB09", "MCP must refuse private repos (fail closed).", "HISTORICAL", "before 2026-08-07", "2026-08-07", ["icarus:D18", "icarus:C13"], "Exposure transferred to the configuring client instead."),
    ("GB10", "Analytics on by default with opt-out is acceptable.", "HISTORICAL", "2026-08-13", "2026-08-14", ["icarus:D21", "icarus:C14"], "Reversed in a day after a private Q/A leak path was found."),
    ("GB11", "A hand-written, zero-dependency website is the right presentation layer.", "HISTORICAL", "before 2026-08-26", "2026-08-27", ["icarus:D29", "icarus:C10", "icarus:C11"], "'too plain... no soul'; rebuilt in Next/React/three.js."),
    ("GB12", "Three channels only: X, Reddit, HN.", "HISTORICAL", "2026-08-25", "2026-09-04", ["icarus:D25", "icarus:D31", "icarus:C5"], "Superseded in practice; never formally revised."),
    ("GB13", "Private repo storage is isolated per user.", "HISTORICAL", "2026-07-16", "2026-07-28", ["icarus:D11", "icarus:C2"], "Replaced by one shared corpus per private repo."),
    ("GB14", "A generic cross-language import resolver is adequate.", "REJECTED", "2026-07", "2026-07", ["icarus:F09"], "18.1% wrong edges; language-specific resolvers."),
    ("GB15", "Agent Mode's primary user is the coding agent / experienced engineer.", "HISTORICAL", "2026-08-04", "2026-08-29", ["icarus:D30", "icarus:B13"], "Reframed for novice builders."),
]

# ------------------------------------------------------------------ belief transitions
TRANSITIONS = [
    dict(id="BT01", topic="Model provider and privacy posture",
         earlier="Free hosted models (Gemini free + Groq judge), public repos only, because there was no API budget and an 8GB Mac.",
         observation="Free tiers may train on code; private code is the real pain.",
         reconsideration="Private-repo machinery with a deterministic trust interlock (07-05).",
         new="One private-safe paid writer (gemini-paid) for everything; interlock kept so safety is provable, not coincidence.",
         status="CURRENT, but whether the key is on contractual no-train terms is unverified (O5, C17).",
         refs=["icarus:D04", "icarus:D07", "icarus:D09", "icarus:O5"]),
    dict(id="BT02", topic="Are private repos the product?",
         earlier="Shelved (06-29), then built (07-05), then removed from alpha-1 (07-14).",
         observation="Tester build without them; re-understanding of what was being sold.",
         reconsideration="'they're the product.'",
         new="Restored in alpha-5 (07-16); later one shared corpus per private repo (07-28).",
         status="CURRENT", refs=["icarus:D11", "icarus:C12", "icarus:C2"]),
    dict(id="BT03", topic="Who the user / buyer is",
         earlier="v0: founders/CTOs/engineers at 5-20 engineer companies; Icarus: eng/platform leaders as buyer.",
         observation="Outreach actually tested OSS maintainers; Sept content targeted individual devs; Agent Mode reframed for novices.",
         reconsideration="'do not collapse those into one ICP' (Unknowns).",
         new="Hypotheses only: creatives/vibecoders/engineers as adoption wedge; eng leaders as buyer.",
         status="UNRESOLVED: no written ICP as of 2026-09-10.", refs=["icarus:C15", "icarus:O1", "icarus:B13"]),
    dict(id="BT04", topic="What Agent Mode is for",
         earlier="MCP tools giving coding agents context git cannot show (08-04).",
         observation="Value appears only when the tool is called; recall limits on intent-shaped questions; 45 unconfirmed decisions.",
         reconsideration="Who cannot evaluate their agent's recommendations?",
         new="Continuity + judgment scaffold for novice builders; one-tap atomic confirmation (08-29); confirmation in the terminal (09-05).",
         status="CURRENT hypothesis; efficacy vs a good CLAUDE.md unmeasured (O4).", refs=["icarus:D30", "icarus:D32", "icarus:O4", "icarus:F24"]),
    dict(id="BT05", topic="What the bottleneck is",
         earlier="Brain first, eval harness before brain (06-28); engineering is the work.",
         observation="Alpha shipped; outreach began failing (late Jul); launches returned near zero.",
         reconsideration="'business phase begins' (07-16): ICP, pricing, trust, design partners.",
         new="'Nothing is engineering-blocked. Everything is distribution-blocked.'",
         status="CURRENT as belief; behavior lagged (engineering kept winning time until September, C16).",
         refs=["icarus:D02", "icarus:B21", "icarus:C16", "icarus:R8"]),
    dict(id="BT06", topic="Which distribution channel works",
         earlier="Cold email to prospects (~07-30 onward), then weekly YC prospect automation.",
         observation="~104 sends, 0 verified positive; wrong person, unreadable copy, role addresses.",
         reconsideration="Three channels only: X, Reddit, HN (08-25); then PH launch (09-01).",
         new="Reply-guy on X/Reddit plus warm/LinkedIn DMs (09-04); PH/HN/cold email declared dead.",
         status="EVOLVING: no channel has demonstrably produced a connected repo (O8).",
         refs=["icarus:F31", "icarus:D25", "icarus:D31", "icarus:O8", "icarus:R12"]),
    dict(id="BT07", topic="Showing failure in public",
         earlier="Posted vulnerable / failure content; it performed best on his own data.",
         observation="Decided the public persona should not showcase own failures or zeros.",
         reconsideration="Values over measured engagement, written down as such.",
         new="No public disclosure of own failures; specific over personal. Inverted for investors (never bluff).",
         status="CURRENT; tension with 'the evidence is the marketing' unresolved (C7).",
         refs=["icarus:D22", "icarus:B26", "icarus:B27", "icarus:C7", "icarus:R11"]),
    dict(id="BT08", topic="Do tool descriptions change agent behaviour?",
         earlier="0/11 unprompted calls -> 4/4 after rewrite (08-11).",
         observation="The 4/4 came from one shared session, violating the plan.",
         reconsideration="Re-ran across independent sessions.",
         new="Quote '1 of 4, independent sessions'; still believes event triggers matter more than capability descriptions (exploratory).",
         status="CURRENT (corrected); stale '0/11 -> 4/4' still in a content note (C8).",
         refs=["icarus:D19", "icarus:D26", "icarus:B34", "icarus:C8", "icarus:F25"]),
    dict(id="BT09", topic="Is Icarus measurably better for agents?",
         earlier="'25% better' posted on X without measurement.",
         observation="Measured: 6/6 in both arms; no raw difference.",
         reconsideration="Value appears only when the tool is actually called (2/4).",
         new="Claims must have the comparison exist before posting; the real signal is tool invocation.",
         status="CURRENT", refs=["icarus:F27", "icarus:B07"]),
    dict(id="BT10", topic="How to detect fabricated answers",
         earlier="Score output against evidence lexically (evals/attribution.py).",
         observation="Fabrications reuse evidence words, so they scored higher than honest paraphrase.",
         reconsideration="Post-hoc lexical detection of composition fails.",
         new="Only compare things to each other, never score against evidence; deterministic guards plus per-claim self-report (advisory).",
         status="CURRENT", refs=["icarus:F04", "icarus:B04", "icarus:F03"]),
    dict(id="BT11", topic="Dependencies",
         earlier="Stdlib by default for everything.",
         observation="512-token embedder silently reading 1/4 of each chunk; plain site judged soulless.",
         reconsideration="A dependency may earn its place with a measurement.",
         new="tree-sitter on measured evidence (recall 69.2% -> 92.3%); full React/three.js stack for the website only.",
         status="EVOLVING: strict for the brain, relaxed for presentation.",
         refs=["icarus:D12", "icarus:D29", "icarus:B16", "icarus:C10"]),
    dict(id="BT12", topic="Hosting and cost",
         earlier="Free hosting (Render free tier; HF Spaces planned).",
         observation="0.1 CPU killed a private connect mid-embed.",
         reconsideration="Paid Azure Container Apps (07-12).",
         new="Azure (~Rs 5,600-6,200/mo) unaffordable -> Oracle Always Free with an abort rule to a ~Rs 430-550 paid floor; free infra worth only ~Rs 500/mo once risk is priced.",
         status="AUTHORIZED, NOT RUN at 2026-09-10.", refs=["icarus:D10", "icarus:D33", "icarus:B31", "icarus:F23"]),
    dict(id="BT13", topic="Analytics and observability vs privacy",
         earlier="Analytics default-on with opt-out (08-13).",
         observation="Default-on path could export private Q/A via MCP.",
         reconsideration="'Absence is not consent.'",
         new="Counts-only by default, opt-in content; no third-party script on the site (08-17).",
         status="CURRENT; consequence: site conversion unobservable (O9), distinct users maybe uncountable (O10).",
         refs=["icarus:D21", "icarus:D24", "icarus:O9", "icarus:O10"]),
    dict(id="BT14", topic="Product data-retention claim",
         earlier="Vault and product philosophy: data 'discarded after each request'.",
         observation="2026-09-05 audit: corpora and decisions are durable until deletion.",
         reconsideration="Repo docs corrected (uncommitted).",
         new="Durable until deletion.",
         status="UNRESOLVED in the vault (still says discard).", refs=["icarus:C1", "icarus:O20"]),
    dict(id="BT15", topic="Career framing",
         earlier="LinkedIn headline 'Open to Early-Stage Roles'.",
         observation="(Not recorded.)",
         reconsideration="Headline changed to founder framing on 2026-09-04.",
         new="Six SDR/BDR applications by 2026-09-07; DevTools resume on 2026-09-10, while Icarus continued.",
         status="UNCERTAIN: founder path vs job outcome unknown after 2026-09-10.",
         refs=["icarus:FACT01L32", "icarus:O27", "icarus:C9"]),
    dict(id="BT16", topic="Proof pages",
         earlier="Per-prospect proof pages.",
         observation="'proof with no next step'; three pages 404'd in prod.",
         reconsideration="CTA is the download; outreach list-gated (08-17).",
         new="Proof pages killed, yet an uptimepage results page made for a warm contact on 2026-09-10.",
         status="UNRECONCILED (C6).", refs=["icarus:D23", "icarus:F32", "icarus:C6"]),
    dict(id="BT17", topic="Hacker News",
         earlier="'one clean shot'.",
         observation="Read HN guidelines; 1 point, author comments auto-flagged (karma 1).",
         reconsideration="'worth another attempt' (same day), later HN declared dead (09-04).",
         new="HN parked; lead source vs channel still open.",
         status="EVOLVING / paused (O29).", refs=["icarus:C20", "icarus:F33", "icarus:O29"]),
]

# ------------------------------------------------------------------ decisions
# normalized status, outcome, reversed_by / superseded_by, alternatives (if recorded elsewhere)
DECISIONS = {
    "D01": ("ACTIVE", "Phase 1 built from zero the next day; Icarus became the line of work.", None),
    "D02": ("ACTIVE", "Faces (voice, overlay, web) built after the brain passed its gates (06-30 to 07-03).", None),
    "D03": ("ACTIVE", "Reproducible board; /status reports pinned: true.", None),
    "D04": ("REVERSED", "Replaced by private repos + paid single writer.", "D07, D09, D11"),
    "D05": ("ACTIVE", "Per-tenant isolation; single-tenant kept as upsell.", None),
    "D06": ("ACTIVE", "Push never built; capture partially built via Agent Mode.", None),
    "D07": ("ACTIVE", "Kept after one-model decision; challenged by 2026-09-05 audit (O5).", None),
    "D08": ("ACTIVE", "fastembed bge-small beat BM25; hosted embeddings removed 07-18.", None),
    "D09": ("ACTIVE", "One private-safe writer serves all repos.", None),
    "D10": ("BEING_REVERSED", "Azure judged unaffordable on 2026-09-10.", "D33"),
    "D11": ("ACTIVE", "Refined 07-28 to one shared corpus per private repo.", None),
    "D12": ("ACTIVE", "Semantic recall@5 69.2% -> 92.3%.", None),
    "D13": ("ACTIVE", "Guard (c) live in prod.", None),
    "D14": ("ACTIVE", "Tour shipped purpose/stack/recent; architecture replaced by writer-free structure step.", None),
    "D15": ("ACTIVE", "Signature-level guarantee in code.", None),
    "D16": ("ACTIVE", "Recorded decision doc.", None),
    "D17": ("ACTIVE", "A human-confirmed decision reached PR #17 on 2026-08-31 (audit E-7).", None),
    "D18": ("ACTIVE", "Tradeoff accepted openly.", None),
    "D19": ("ACTIVE", "Headline effect later corrected from 4/4 to 1/4.", "claim revised by D26"),
    "D20": ("ACTIVE", "First sign-in narrowed to read:user.", None),
    "D21": ("ACTIVE", "Closed a private Q/A export path.", None),
    "D22": ("ACTIVE", "Public rule; inverted for investors.", None),
    "D23": ("ACTIVE", "Contradicted in practice by a 09-10 results page (C6).", None),
    "D24": ("ACTIVE", "Site conversion unobservable (O9).", None),
    "D25": ("SUPERSEDED", "LinkedIn and PH added; HN/PH then declared dead.", "D31"),
    "D26": ("ACTIVE", "Public self-correction; stale 4/4 remains in a content note (C8).", None),
    "D27": ("ACTIVE", "Temporal flag found never firing live, then fixed and measured 3/3 (08-27).", None),
    "D28": ("UNKNOWN_OUTCOME", "No record after 2026-08-26.", None),
    "D29": ("ACTIVE", "Site live on Vercel; binaries on GitHub Releases.", None),
    "D30": ("ACTIVE", "45 candidates went unconfirmed behind a GUI, prompting D32.", None),
    "D31": ("ACTIVE", "50-user goal; no channel yet shown to produce connected repos.", None),
    "D32": ("BUILT_UNCOMMITTED", "Built, uncommitted at snapshot (O20).", None),
    "D33": ("AUTHORIZED_NOT_RUN", "Empty canary deleted (Rs 1,550/mo); migration not run by 09-10.", None),
    "D34": ("ACTIVE", "Policy for OSS contributions.", None),
    "D35": ("ACTIVE", "Substack title rule.", None),
}

DECISION_PATTERNS = [
    dict(id="DP01", pattern="Decide fast, record the reason, reverse cleanly and record the reversal.",
         evidence=["icarus:D04", "icarus:D11", "icarus:D25", "icarus:D29", "icarus:C11", "icarus:C14", "icarus:R5"],
         domains=["engineering", "product", "design", "distribution"], persistence="CROSS-DOMAIN, SINGLE PROJECT"),
    dict(id="DP02", pattern="Encode trust as structure (signatures, interlocks, gates) rather than policy.",
         evidence=["icarus:D07", "icarus:D13", "icarus:D15", "icarus:D16", "icarus:D17", "icarus:D21", "icarus:D27", "icarus:R9"],
         domains=["engineering", "privacy"], persistence="SINGLE PROJECT (strong)"),
    dict(id="DP03", pattern="Let a measurement choose: dependencies, features and claims must be earned by data.",
         evidence=["icarus:D08", "icarus:D12", "icarus:D14", "icarus:D26", "icarus:R15"],
         domains=["engineering", "product", "public claims"], persistence="CROSS-DOMAIN, SINGLE PROJECT"),
    dict(id="DP04", pattern="Narrow engineering scope to the smallest provable unit under a large vision.",
         evidence=["icarus:D02", "icarus:D03", "icarus:D09", "icarus:D20", "icarus:R1"],
         domains=["engineering"], persistence="SINGLE PROJECT; v0 -> Icarus vision persistence"),
    dict(id="DP05", pattern="Under distribution pressure, add or switch channels before a single-variable test completes.",
         evidence=["icarus:D23", "icarus:D25", "icarus:D31", "icarus:R12"],
         domains=["distribution"], persistence="SINGLE PROJECT; MEDIUM-HIGH. Source notes similar playbook-hunting for Tempo/Signal (MEDIUM)."),
    dict(id="DP06", pattern="Decide against own data when values conflict, and write down that he did.",
         evidence=["icarus:D22", "icarus:D18", "icarus:R11"], domains=["content", "privacy"], persistence="SINGLE PROJECT; n=2"),
    dict(id="DP07", pattern="Attach dated checkpoints and explicit abort conditions.",
         evidence=["icarus:D28", "icarus:D33", "icarus:R14"], domains=["business", "infrastructure"], persistence="SINGLE PROJECT"),
    dict(id="DP08", pattern="Cash is the forcing function for infrastructure choices.",
         evidence=["icarus:D04", "icarus:D08", "icarus:D10", "icarus:D33"], domains=["infrastructure"], persistence="SINGLE PROJECT; constraint, not preference"),
    dict(id="DP09", pattern="Keep a human authority boundary: agents propose, a person confirms, nothing merges itself.",
         evidence=["icarus:D17", "icarus:D30", "icarus:D32", "icarus:D34"], domains=["product", "AI collaboration"], persistence="SINGLE PROJECT; mirrors his own agent-delegation style (05_WORKING_STYLE)"),
]

# ------------------------------------------------------------------ contradictions
CONTRADICTION_STATUS = {  # source contradictions: compiler classification
    "C1": "UNRESOLVED", "C2": "INTENTIONAL_EVOLUTION (stale docs remain)", "C3": "UNRESOLVED (documentation drift)",
    "C4": "KNOWN DRIFT", "C5": "INTENTIONAL_EVOLUTION (never formally revised)", "C6": "UNRECONCILED",
    "C7": "PARTIALLY SCOPED", "C8": "UNRESOLVED (stale claim)", "C9": "UNRESOLVED", "C10": "INTENTIONAL_EVOLUTION",
    "C11": "INTENTIONAL_EVOLUTION", "C12": "INTENTIONAL_EVOLUTION", "C13": "INTENTIONAL_EVOLUTION",
    "C14": "INTENTIONAL_EVOLUTION", "C15": "UNRESOLVED", "C16": "UNRESOLVED", "C17": "UNRESOLVED",
    "C18": "STALE BELIEF", "C19": "SUPERSEDED (memory not deleted)", "C20": "INTENTIONAL_EVOLUTION",
    "C21": "OPEN RISK", "C22": "UNRESOLVED", "C23": "UNVERIFIABLE",
}

GLOBAL_CONTRADICTIONS = [
    dict(id="GC01", kind="principle vs behavior",
         a="Unknown must never render as a number or zero (B03).", b="His own retry script turned failed lookups into 0 the same day he logged the lesson.",
         when_a="2026-07 onward", when_b="same day as the lesson (date not given)",
         explanation="Knowing a failure mode is not designing against it (L7). The source records it as a counterexample.",
         status="RECORDED, not recurring evidence", refs=["icarus:B03", "icarus:L7"]),
    dict(id="GC02", kind="principle vs behavior",
         a="With investors, the no-bluff rule binds the founder too (B27); every number read back against its source (B07).",
         b="Resume: 'sold to engineering leaders', '~75% cloud cost cut', 'Founder Mar 2026'. Record: zero paying customers, 25% realized, repo begins 06-27.",
         when_a="2026-08-24 onward", when_b="2026-09-07 to 2026-09-10",
         explanation="Possibly different norms applied to job-search material than to investor material; no statement from him. Do not resolve.",
         status="UNRESOLVED", refs=["icarus:B27", "icarus:B07", "icarus:C9"]),
    dict(id="GC03", kind="stated priority vs time allocation",
         a="'business decisions, not new engineering' (from 07-16); 'nothing is engineering-blocked'.",
         b="309 commits in July, 206 in August; ICP and pricing never written.",
         when_a="2026-07-16", when_b="2026-07 to 2026-08",
         explanation="Engineering is where he and his agents are most productive; business questions lacked a forcing function (INFERRED).",
         status="UNRESOLVED", refs=["icarus:C16", "icarus:O1", "icarus:O2", "icarus:B21"]),
    dict(id="GC04", kind="method inconsistency across domains",
         a="Engineering: one variable, pre-registered, n stated, abort rules.",
         b="Distribution: email -> X -> LinkedIn -> Substack -> HN -> PH -> Reddit -> LinkedIn within ~5 weeks; three-channel rule broken within ~10 days.",
         when_a="Aug 2026", when_b="Aug to Sep 2026",
         explanation="Rigor tracks what he can instrument; channels were left uninstrumented by choice (no site analytics). Compiler inference.",
         status="UNRESOLVED", refs=["icarus:R12", "icarus:R18", "icarus:D25", "icarus:D24"]),
    dict(id="GC05", kind="belief vs action",
         a="Pull beats push for developer audiences; buyers ignore cold email (B28).",
         b="LinkedIn outreach with connection notes and DMs adopted 2026-09-04/10.",
         when_a="2026-09-02", when_b="2026-09-04 to 2026-09-10",
         explanation="Possibly 'push' means templated cold email only, and warm/personal DMs are a separate category (B30). Not stated.",
         status="UNRESOLVED (definition unclear)", refs=["icarus:B28", "icarus:B30", "icarus:D31"]),
    dict(id="GC06", kind="contradictory goals",
         a="Founder visibility for Icarus and Alankrit personally (from 2026-09-08).",
         b="SDR/BDR and DevTools job applications (from 2026-09-07).",
         when_a="2026-09-08", when_b="2026-09-07",
         explanation="Could be complementary (visibility helps either path) or competing for time; the source graph says 'competes with'.",
         status="UNRESOLVED", refs=["icarus:O27", "icarus:FACT01L32"]),
    dict(id="GC07", kind="documentation principle vs drift",
         a="Files are the memory; one home per item; HANDOFF is 'the one doc kept current'.",
         b="HANDOFF stale since 08-11, STRATEGY describes the wrong chunking, vault says data is discarded, content note cites retired 4/4.",
         when_a="2026-06-28 onward", when_b="2026-08-11 to 2026-09-10",
         explanation="Process volume exceeded maintenance capacity (580KB vault, 7,269-line HANDOFF). INFERRED.",
         status="RECURRING", refs=["icarus:B20", "icarus:C1", "icarus:C3", "icarus:C4", "icarus:C8"]),
    dict(id="GC08", kind="principle vs artifact",
         a="Never fabricate citations or evidence (standing order to agents; the product's non-negotiable).",
         b="The site's own honesty section showed three citation chips from different repos as one answer.",
         when_a="always", when_b="2026-08/09 (date not given)",
         explanation="Decorative design work by agents bypassed the honesty discipline; he caught it by eye.",
         status="FIXED (caught), lesson open", refs=["icarus:F30", "icarus:B01"]),
    dict(id="GC09", kind="scope of the corpus vs scope of this compilation",
         a="This compilation is framed as a cross-project Global Context Layer.",
         b="The source corpus holds exactly one project extraction (Icarus), plus indirect evidence of JARVIS v0.",
         when_a="2026-10-03", when_b="2026-10-03",
         explanation="Other projects were deliberately out of scope for the extraction. Every 'recurring' claim here is cross-domain within one project unless marked otherwise.",
         status="STRUCTURAL GAP", refs=["icarus:MANIFEST"]),
]

# ------------------------------------------------------------------ open loops (global)
GLOBAL_OPEN_LOOPS = [
    dict(id="GO01", q="Founder path or employment?", first="2026-09-04", last="2026-09-10", projects=["icarus", "job-search-2026-09"],
         understanding="Both active concurrently; cash pressure high.", why="No evidence after 2026-09-10.", importance="CRITICAL", status="OPEN",
         refs=["icarus:O27", "global:GC06"]),
    dict(id="GO02", q="How does Alankrit get an audience for what he builds?", first="~2026-07-30", last="2026-09-10", projects=["icarus"],
         understanding="Every launch/cold channel near zero; warm DMs and specific replies showed small-n signal. Source says distribution recurred for Tempo/Signal (MEDIUM).",
         why="No channel has been instrumented to show a connected repo.", importance="CRITICAL", status="OPEN",
         refs=["icarus:O8", "icarus:B21", "global:BT06"]),
    dict(id="GO03", q="What happened between 2026-09-10 and 2026-10-03?", first="2026-10-03", last="2026-10-03", projects=["icarus"],
         understanding="No evidence.", why="Extraction stops at 2026-09-10.", importance="HIGH", status="EVIDENCE GAP", refs=["icarus:T46"]),
    dict(id="GO04", q="Why was JARVIS v0 reset, and why the name 'Icarus'?", first="2026-06-27", last="2026-10-03", projects=["jarvis-v0", "icarus"],
         understanding="Only 'new direction'.", why="No record found.", importance="MEDIUM", status="EVIDENCE GAP", refs=["icarus:D01"]),
    dict(id="GO05", q="What happened March to June 2026 (resume says founder from March)?", first="2026-03", last="2026-06-27", projects=["icarus"],
         understanding="Unknown.", why="Repo begins 2026-06-27.", importance="MEDIUM", status="EVIDENCE GAP", refs=["icarus:T02", "icarus:C9"]),
    dict(id="GO06", q="Do the patterns seen in Icarus hold in his other projects?", first="2026-10-03", last="2026-10-03",
         projects=["Signal", "Tempo", "Pantheon.ai", "Marketing Intelligence", "Solar Forecasting", "Job Application Context"],
         understanding="Not extracted.", why="Out of scope for the only extraction.", importance="HIGH", status="EVIDENCE GAP", refs=["icarus:MANIFEST"]),
    dict(id="GO07", q="Outcome of the YC application drafted 2026-07-22?", first="2026-07-22", last="2026-07-22", projects=["icarus"],
         understanding="Unknown.", why="No record.", importance="MEDIUM", status="EVIDENCE GAP", refs=["icarus:T19"]),
    dict(id="GO08", q="Will he write the ICP and pricing, or is the company question deferred indefinitely?", first="2026-07-16", last="2026-09-10", projects=["icarus"],
         understanding="Flagged since 07-16; blocks Antler and investors.", why="Engineering and channels absorbed the time (GC03).", importance="CRITICAL", status="OPEN",
         refs=["icarus:O1", "icarus:O2", "icarus:O24", "global:GC03"]),
]

# ------------------------------------------------------------------ recurring lessons
RECURRING_LESSONS = [
    dict(id="RL01", lesson="Groundedness is not relevance is not truth.", failures=["F01", "F02", "F03", "F13"],
         changed="YES: guard (c), selection marker, per-claim self-report.", reappeared="Three separate recurrences before the principle held; then first measured wrong answer (F13).",
         refs=["icarus:B02", "icarus:L7"]),
    dict(id="RL02", lesson="A system that fails safe (or silent) hides its own bugs; only a real end-to-end action finds them.",
         failures=["F05", "F14", "F15", "F18", "F19", "F20", "F21", "F22", "F06", "F10"],
         changed="PARTIAL: successor probe, live guard measurement for one guard; other guards unmeasured (O15).",
         reappeared="Recurs from 2026-07-13 to 2026-09-05.", refs=["icarus:L1", "icarus:B18", "icarus:O15"]),
    dict(id="RL03", lesson="A measurement's blind spot reads as a result; name what else changed before trusting a number.",
         failures=["F04", "F07", "F25", "F26", "F27", "F28", "F29", "F16"],
         changed="YES: PROTOCOL.md (one rule per failure), public retraction of 4/4, read-back rule.",
         reappeared="Agent-quota and harness-config contamination kept recurring through Aug.", refs=["icarus:L2", "icarus:L3", "icarus:B05", "icarus:B06"]),
    dict(id="RL04", lesson="The thing was fine; the wording (register) was wrong.", failures=["F31", "F36", "F11"],
         changed="YES: voice rules, decision-shaped prompts, event-triggered tool descriptions.", reappeared="Three times: cold email, tool descriptions, social copy.",
         refs=["icarus:L4", "icarus:B23"]),
    dict(id="RL05", lesson="Volume is not a diagnosis; activity is not authority; a raw count is not a human count.",
         failures=["F31", "F38", "F35"], changed="YES: list-gated outreach, mergedBy for authority, bot filtering.",
         reappeared="Distribution still channel-hopping afterwards (GC04).", refs=["icarus:B22", "icarus:R10"]),
    dict(id="RL06", lesson="Launch platforms need a pre-built audience and account standing.", failures=["F33", "F34", "F35"],
         changed="YES: PH/HN declared dead; reply-guy to build standing.", reappeared="Reddit new-account filters repeated the HN karma problem.", refs=["icarus:D31"]),
    dict(id="RL07", lesson="Capture without frictionless human confirmation produces no memory.", failures=["F24"],
         changed="YES: terminal confirmation (D32).", reappeared="Single instance.", refs=["icarus:D32", "icarus:B11"]),
    dict(id="RL08", lesson="First question about a cost: what is running at all. A lock encodes an intention at a moment.", failures=["F23"],
         changed="YES: canary deleted; Oracle plan.", reappeared="Single instance.", refs=["icarus:L6", "icarus:D33"]),
    dict(id="RL09", lesson="Correcting an overstatement invites the opposite overstatement (AI audits included).", failures=["F29"],
         changed="UNKNOWN", reappeared="Single instance.", refs=["icarus:B08"]),
]

# failures: changed later behavior? (YES / PARTIAL / NO / UNKNOWN) - judged from the source text's follow-up arrows
FAILURE_CHANGED = {
    "F01": "YES", "F02": "YES", "F03": "YES", "F04": "YES", "F05": "YES", "F06": "YES", "F07": "YES", "F08": "UNKNOWN",
    "F09": "YES", "F10": "UNKNOWN", "F11": "YES", "F12": "NO (open; needs dependency decision)", "F13": "PARTIAL (HEAD check unbuilt, O14)",
    "F14": "PARTIAL", "F15": "YES", "F16": "PARTIAL", "F17": "UNKNOWN (pilot paused)", "F18": "YES (fixed in 0.1.13)", "F19": "YES",
    "F20": "UNKNOWN", "F21": "UNKNOWN", "F22": "UNKNOWN", "F23": "YES", "F24": "YES", "F25": "YES", "F26": "YES", "F27": "YES",
    "F28": "UNKNOWN", "F29": "UNKNOWN", "F30": "YES (caught)", "F31": "YES", "F32": "YES", "F33": "YES", "F34": "YES",
    "F35": "UNKNOWN", "F36": "YES", "F37": "UNKNOWN", "F38": "YES",
}

# ------------------------------------------------------------------ interests
INTERESTS = [
    ("IN01", "AI honesty, grounding and abstention", ["bluff", "honest", "abstain", "abstention", "grounded", "groundedness", "cite", "citation", "fabricat"], "INTRINSIC", "PERSISTENT", "Predates Icarus (v0 'cannot bluff')."),
    ("IN02", "Retrieval / RAG engineering", ["retriev", "embedd", "bm25", "chunk", "recall", "rag "], "INSTRUMENTAL", "CURRENT", "Means to the honesty product; also prior-role work (RAG content tools)."),
    ("IN03", "AI coding agents and how they fail", ["agent", "mcp", "claude", "codex"], "INTRINSIC (INFERRED, MEDIUM)", "INCREASING through Aug", "Prior role 'Agentic AI Engineer'; Pantheon.ai; Agent Mode; his own way of building."),
    ("IN04", "Organizational memory / preserving intent", ["intent", "organizational memory", "organisational memory", "engineering memory", "organisation brain", "decision history", "refused", "rejected attempt", "written down", "unrecorded"], "INTRINSIC", "PERSISTENT", "v0 question 'why was this decision made' carried into Icarus."),
    ("IN05", "Measurement and experimental method", ["measur", "experiment", "pre-regist", "preregist", "protocol", "n=", "baseline"], "INSTRUMENTAL -> SIGNATURE (INFERRED)", "CURRENT", "Named 'the unusual asset' in his own Work Queue."),
    ("IN06", "Privacy and trust boundaries", ["privacy", "private", "trust", "consent", "train", "isolation", "credential"], "INSTRUMENTAL", "CURRENT", "Product requirement turned design principle."),
    ("IN07", "Distribution and go-to-market", ["distribution", "outreach", "channel", "cold email", "launch", "reddit", "linkedin", "product hunt", "show hn", "reply-guy", "users"], "INSTRUMENTAL", "INCREASING (dominant by Sept)", "The recurring hard problem."),
    ("IN08", "Writing voice and content craft", ["voice rule", "voice profile", "posts", "posted", " copy", "substack", "register", "em-dash", "carousel", "headline", "x content", "thread"], "UNCERTAIN (instrumental for distribution; strong personal rules)", "INCREASING", "Hard voice rules repeated across surfaces."),
    ("IN09", "Visual and motion design / taste", ["design", "soul", "motion", "three.js", "logo", "visual", "dark"], "INTRINSIC (MEDIUM)", "CURRENT", "Tempo (screenshots to motion video); 'no soul' as rejection reason."),
    ("IN10", "Native macOS apps", ["mac app", "macos", "swiftui", "dmg", "notariz", "gatekeeper", "hotkey"], "INTRINSIC (MEDIUM)", "CURRENT", "Signal, 'first macOS app', Icarus Mac app."),
    ("IN11", "Startup strategy and funding", ["yc", "antler", "investor", "pricing", "icp", "moat", "wedge", "business"], "INSTRUMENTAL", "CURRENT but stalled", "ICP/pricing never written."),
    ("IN12", "Infrastructure cost and survival", ["azure", "oracle", "render", "cost", "bill", "₹", "hosting", "free tier"], "INSTRUMENTAL", "INCREASING (Sept)", "Cash is the binding constraint."),
    ("IN13", "Career / employment", ["resume", "job", "sdr", "bdr", "application"], "INSTRUMENTAL", "EMERGING (Sept)", "Parallel search from 2026-09-07."),
    ("IN14", "Voice interfaces and the JARVIS scene", ["jarvis", "voice", "overlay", "hotkey"], "INTRINSIC", "PERSISTENT (as vision), de-prioritized in practice", "Founding image since v0."),
    ("IN15", "Workflow automation", ["automat", "workflow", "pipeline", "crm"], "UNCERTAIN", "HISTORICAL->CURRENT", "Prior roles and Signal; within Icarus, mostly CI and outreach automation."),
]

INTEREST_EDGES = [
    ("IN01", "IN04"), ("IN01", "IN05"), ("IN01", "IN06"), ("IN02", "IN01"), ("IN03", "IN04"), ("IN03", "IN01"),
    ("IN07", "IN08"), ("IN07", "IN11"), ("IN12", "IN13"), ("IN14", "IN10"), ("IN09", "IN10"), ("IN05", "IN07"),
    ("IN11", "IN07"), ("IN15", "IN03"),
]

# ------------------------------------------------------------------ voice examples
# (id, category list, provenance, source file, exact excerpt, why it represents his voice)
VOICE_EXAMPLES = [
    ("V01", ["argument", "short-form"], "POSTED", "06_VOICE_PROFILE.md", "Code shows what exists. Not why it exists.", "Signature two-sentence contrast; the thesis in eight words."),
    ("V02", ["argument", "short-form"], "POSTED", "06_VOICE_PROFILE.md", "A merged PR leaves a commit. A refused one leaves nothing.", "Parallel-structure contrast, concrete nouns, no adjectives."),
    ("V03", ["argument"], "POSTED", "06_VOICE_PROFILE.md", "The winner won't be whoever produces the most code. It'll be whoever gives that code meaning.", "Longer contrast; worldview stated through the market."),
    ("V04", ["humor", "short-form", "reflection"], "POSTED", "06_VOICE_PROFILE.md", "Not the strongest traditional dev. But I ship fast.", "Flat self-deprecation, no apology; the closest thing to humor in the corpus."),
    ("V05", ["directness", "short-form"], "POSTED", "06_VOICE_PROFILE.md", "Reply if you're interested.", "Unadorned ask; no softening."),
    ("V06", ["explanation", "short-form"], "POSTED", "06_VOICE_PROFILE.md", "Watched a coding agent about to...", "Opens on an observation, product second."),
    ("V07", ["disagreement", "directness"], "HIS_FEEDBACK", "06_VOICE_PROFILE.md", "Substack articles do not have a character limit.", "Disagrees by stating a fact, flat and brief."),
    ("V08", ["disagreement", "technical reasoning"], "HIS_FEEDBACK", "06_VOICE_PROFILE.md", "sending over an indexed query search along with results means nothing to the receivers.", "Lowercase, phone-typed critique; judges by the receiver's experience."),
    ("V09", ["short-form"], "POSTED", "06_VOICE_PROFILE.md", "Icarus tells it first. Live today.", "Marked natural: short line, present tense, no explanation."),
    ("V10", ["short-form"], "POSTED", "06_VOICE_PROFILE.md", "17,810 agent skills in one library.", "Unrounded number as the hook; chosen over a personal framing."),
    ("V11", ["counter-example"], "REJECTED", "06_VOICE_PROFILE.md", "It reads a repository's code and GitHub history, then returns cited context or an honest unknown.", "Rejected as institutional register. Shows what not to write."),
    ("V12", ["counter-example"], "REJECTED", "06_VOICE_PROFILE.md", "A maintainer decides in about five seconds", "Rejected: aphorism without a measured number."),
    ("V13", ["directness", "disagreement"], "HIS_FEEDBACK", "04_REASONING_PATTERNS.md", "generalised crap", "Blunt rejection of vague output; the only profanity-adjacent phrase in the corpus."),
    ("V14", ["directness"], "HIS_FEEDBACK", "02_DECISION_REGISTER.md", "too plain... no soul.", "Design feedback in three words; taste as a rejection reason."),
    ("V15", ["directness", "argument"], "HIS_FEEDBACK", "02_DECISION_REGISTER.md", "they're the product.", "A whole reversal justified in three words."),
    ("V16", ["argument", "technical reasoning"], "HIS_FRAMING", "04_REASONING_PATTERNS.md", "Nothing is engineering-blocked. Everything is distribution-blocked", "Names the binding constraint with a mirrored pair."),
    ("V17", ["technical reasoning"], "DOC_PHRASE", "04_REASONING_PATTERNS.md", "A signature that cannot accept a question is stronger than a policy saying we won't pass one.", "Structural guarantee over policy, stated as a comparison."),
    ("V18", ["reflection"], "DOC_PHRASE", "04_REASONING_PATTERNS.md", "Reversing cleanly is a feature", "Reframes changing his mind as a property, not a cost."),
    ("V19", ["reflection", "technical reasoning"], "DOC_PHRASE", "08_FAILURES_AND_LESSONS.md", "A system that fails safe hides its own bugs.", "Lesson compressed into one declarative."),
    ("V20", ["reflection"], "DOC_PHRASE", "08_FAILURES_AND_LESSONS.md", "Before reading a number as evidence, name what else changed.", "Imperative rule derived from a failure."),
    ("V21", ["reflection"], "DOC_PHRASE", "08_FAILURES_AND_LESSONS.md", "The thing being described was fine; the wording was wrong.", "Recurring self-diagnosis (three times)."),
    ("V22", ["reflection", "long-form"], "DOC_PHRASE", "08_FAILURES_AND_LESSONS.md", "A lock encodes an intention at a moment; it does not notice when the thing it protects stops existing.", "Longest aphoristic lesson; still one sentence."),
    ("V23", ["reflection"], "DOC_PHRASE", "08_FAILURES_AND_LESSONS.md", "Knowing a failure mode is not the same as designing against it.", "Self-critical, general, testable."),
    ("V24", ["technical reasoning", "directness"], "HIS_RULE", "00_PROJECT_CONTEXT.md", "Never say 'I don't know is always provable in code.'", "Precision about what a guarantee covers; forbids his own overclaim."),
    ("V25", ["short-form", "argument"], "POSTED", "00_PROJECT_CONTEXT.md", "Git remembers what changed. Icarus remembers why.", "Tagline built on the same contrast move."),
    ("V26", ["argument"], "DOC_PHRASE", "00_PROJECT_CONTEXT.md", "Explanation is the wedge; organizational memory is the product", "Strategy stated as a two-clause contrast."),
    ("V27", ["short-form", "directness"], "DOC_PHRASE", "02_DECISION_REGISTER.md", "Absence is not consent.", "Four-word principle closing a privacy decision."),
    ("V28", ["directness"], "DOC_PHRASE", "02_DECISION_REGISTER.md", "proof with no next step", "Kills a tactic with a five-word diagnosis."),
    ("V29", ["directness"], "HIS_FEEDBACK", "02_DECISION_REGISTER.md", "do not resurrect", "Closes the door on v0 without discussion."),
    ("V30", ["technical reasoning"], "AI_HOUSE_STYLE", "06_VOICE_PROFILE.md", "attempts: the deferral flag never fired live, so let it fetch the successor", "Commit subject written by agents under his direction: finding-first, plain, slightly wry. Not his direct voice."),
    ("V31", ["technical reasoning"], "AI_HOUSE_STYLE", "06_VOICE_PROFILE.md", "site: don't claim the model provider doesn't train on your code", "House style: the commit states the honesty correction."),
    ("V32", ["short-form", "directness"], "HIS_RULE", "06_VOICE_PROFILE.md", "you seem like a good conversation to have, let's connect", "His specified LinkedIn close: plain, no question, no cliche."),
    ("V33", ["argument"], "HIS_FRAMING", "01_ALANKRIT_CONTEXT.md", "fluent like JARVIS, honest about what it knows", "Ambition expressed through the product scene, not personal grandiosity."),
    ("V34", ["argument", "technical reasoning"], "DOC_PHRASE", "01_ALANKRIT_CONTEXT.md", "Build the brain as a typed API first; sell it typed.", "Business strategy as an engineering instruction."),
    ("V35", ["technical reasoning"], "DOC_PHRASE", "02_DECISION_REGISTER.md", "on measured evidence, not a hunch.", "Why a dependency was allowed; evidence over intuition."),
]

# ------------------------------------------------------------------ extra knowledge-graph edges
EXTRA_EDGES = [
    ("icarus:F01", "led_to", "icarus:D13"), ("icarus:F04", "led_to", "global:BT10"), ("icarus:F24", "led_to", "icarus:D32"),
    ("icarus:F23", "led_to", "icarus:D33"), ("icarus:F25", "led_to", "icarus:D26"), ("icarus:F31", "led_to", "icarus:D23"),
    ("icarus:F38", "led_to", "icarus:D23"), ("icarus:F33", "led_to", "icarus:D31"), ("icarus:F34", "led_to", "icarus:D31"),
    ("icarus:F06", "led_to", "icarus:D12"), ("icarus:D04", "superseded_by", "icarus:D09"), ("icarus:D04", "reversed", "icarus:D11"),
    ("icarus:D10", "superseded_by", "icarus:D33"), ("icarus:D25", "superseded_by", "icarus:D31"), ("icarus:D19", "superseded_by", "icarus:D26"),
    ("icarus:D30", "led_to", "icarus:D32"), ("icarus:D06", "led_to", "icarus:D30"), ("icarus:B01", "supported", "icarus:D07"),
    ("icarus:B02", "derived_from", "icarus:F01"), ("icarus:B26", "contradicted", "icarus:B25"), ("icarus:B28", "contradicted", "icarus:D31"),
    ("icarus:B21", "contradicted", "icarus:C16"), ("icarus:B27", "contradicted", "icarus:C9"), ("icarus:B03", "contradicted", "global:GC01"),
    ("icarus:D24", "caused", "icarus:O9"), ("icarus:D21", "caused", "icarus:O10"), ("icarus:D07", "related_to", "icarus:O5"),
]

PEOPLE = [
    ("Alankrit Ghosh", "solo founder; subject of this context", ["icarus", "jarvis-v0"]),
    ("Claude Code (AI agent)", "primary builder and auditor", ["icarus"]),
    ("Codex (AI agent)", "independent reviewer and parallel builder", ["icarus"]),
    ("Harshitha", "barter marketer (D28)", ["harshitha-barter"]),
    ("Artem (@sl1ma4)", "uptimepage run, results page 2026-09-10", ["icarus"]),
]

TECHNOLOGIES = ["Python stdlib", "fastembed", "BM25", "tree-sitter", "Gemini", "Groq", "SwiftUI/AppKit", "Sparkle", "Chrome MV3",
                "Next.js", "three.js", "MCP", "Azure Container Apps", "Render", "Oracle Cloud", "GitLab CI", "Vercel", "PostHog", "GitHub OAuth"]
