"""Phase 7: render human-readable documents.

Data-driven documents are generated from the reconciled model. Narrative
documents (identity, reasoning, working style, voice, global context, handoff)
are authored in compiler/narrative/ with inline [project:ID] references; this
module copies them to the workspace root, and validate.py checks every ref.
"""
from __future__ import annotations

import re
import shutil

import curated as C
from common import COMPILER_DIR, COMPILE_DATE, write_text

NARRATIVE = ["06_ALANKRIT_IDENTITY.md", "07_REASONING_MODEL.md", "08_WORKING_STYLE.md", "09_VOICE_MODEL.md",
             "ALANKRIT_GLOBAL_CONTEXT.md", "HANDOFF_TO_ALANKRIT_OS.md"]

HDR = ("> Generated by `python compiler/run.py` on {date}. Source corpus is read-only; refs like "
       "`[icarus:D07]` resolve to `memory/*.jsonl` and to file:line in the source. "
       "Narrative synthesis covers the Icarus extraction (incl. JARVIS v0 history); other extracted projects are inventoried and "
       "parsed but not yet reconciled. See `00_SOURCE_INVENTORY.md` and `16_VALIDATION_REPORT.md`.\n")


def _c(text):
    return re.sub(r"\s+", " ", str(text or "")).replace("|", "/").strip()


def _src(r):
    s = r.get("source", {})
    return f"`{s.get('file')}:{s.get('line')}`" if "file" in s else ", ".join(f"[{x}]" for x in s.get("derived_from", []))


def _of(model, *types, prefix=None):
    # narrative/registers render only the overlay-reconciled project plus compiler-level records
    return [r for r in model["records"].values() if r["type"] in types and (prefix is None or r["id"].startswith(prefix))
            and r.get("project") in (C.PROJECT, "global", None)]


def doc(name, title, body):
    write_text(name, f"# {title}\n\n{HDR.format(date=COMPILE_DATE)}\n{body.rstrip()}\n")


# ---------------------------------------------------------------- 00 inventory
def inventory(model):
    s = model["scan"]
    lines = [f"Source path: `{s['source_path']}`  ", f"Scanned: {s['scanned_at']}  ",
             f"Directories: {len(s['directories'])} ({', '.join(s['directories'])})  ",
             f"Files: {s['file_count']} · {s['total_bytes']:,} bytes  ",
             f"Projects discovered (by `extraction_manifest.json`): **{len(s['projects'])}**  ",
             f"Unassigned files: {len(s['unassigned_files'])} · Exact duplicates: {len(s['duplicates'])}", ""]
    for p in s["projects"]:
        lines += [f"## Project: {p['name']} (`{p['slug']}`)", "",
                  f"- Root: `{p['root']}` (flat; the corpus root IS the project root)",
                  f"- Extraction date: {p['extraction_date']} · latest evidence: {p['latest_evidence_date']}",
                  f"- Manifest parses: {p['manifest_parses']} · declared counts: {p['declared_counts']}",
                  f"- Declared confidence: {p['declared_confidence']}",
                  f"- Missing expected artifacts: {p['missing_artifacts'] or 'none'}",
                  f"- Unexpected artifacts: {p['unexpected_artifacts'] or 'none'}",
                  f"- Secondary sources the extractor used (not in this corpus): " + "; ".join(p["secondary_sources"]), "",
                  "### Declared coverage gaps (from the manifest)", ""] + [f"- {g}" for g in p["coverage_gaps"]] + [""]
    lines += ["## Files", "", "| file | project | bytes | lines | modified (UTC) | sha256 (12) | issues |", "|---|---|---|---|---|---|---|"]
    for f in s["files"]:
        lines.append(f"| `{f['path']}` | {f['project']} | {f['bytes']} | {f['lines']} | {f['modified'][:19]} | "
                     f"{f['sha256'][:12]} | {', '.join(f['issues']) or 'none'} |")
    parsed = {k: len(v) for k, v in model["by_kind"].items()}
    declared = s["projects"][0]["declared_counts"] if s["projects"] else {}
    lines += ["", "## Parse yield vs manifest declarations", "",
              "| record kind | parsed | declared by extractor |", "|---|---|---|"]
    for kind, key in [("decisions", "major_decisions_found"), ("beliefs", "beliefs_found"),
                      ("open_loops", "open_loops_found"), ("contradictions", "contradictions_found")]:
        lines.append(f"| {kind} | {parsed.get(kind, 0)} | {declared.get(key, '—')} |")
    for kind in ["reasoning", "timeline", "glossary", "facts", "transferable", "voice", "working_style", "alankrit", "project", "handoff"]:
        lines.append(f"| {kind} | {parsed.get(kind, 0)} | — |")
    lines.append(f"| failures / lessons / abandoned | {len(_of(model, 'failure'))} / {len(_of(model, 'lesson'))} / {len(_of(model, 'abandoned'))} | — |")
    lines += ["", "## Quality assessment", "",
              "- **Boundary finding:** one project, not many. The task framing expects a multi-project corpus; the corpus holds a single "
              "extraction of Icarus. JARVIS v0 appears only as history inside it. Six other named projects/directories were "
              "deliberately out of scope for the extractor (see manifest gaps). All 'recurring' patterns in this compilation are "
              "therefore cross-domain within one project, not cross-project.",
              "- **Source quality:** HIGH for decisions, beliefs, failures, voice rules (each line cites repo/vault sources). MEDIUM for "
              "pre-June 2026 history and for anything after 2026-09-10 (none exists). The extractor read no session transcripts, ~40% of "
              "`Learning.md`, and the top of a 7,269-line HANDOFF.",
              "- **Malformed / incomplete artifacts:** none detected (all files parse, fences balance, every expected artifact present).",
              "- **Duplicate material:** no duplicate files. Content overlap is by design: `HANDOFF_TO_ALANKRIT_OS.md` and "
              "`01_ALANKRIT_CONTEXT.md` restate items from 02–11; the compiler cites the most specific file (02/03/08 etc.).",
              "- **Secondary-hand evidence:** the corpus is itself a summary. Voice excerpts are quotations reproduced by the extractor, "
              "not raw posts. Treat every claim as at most one hop from primary evidence.", "",
              "Machine-readable: `source_manifest.json`."]
    doc("00_SOURCE_INVENTORY.md", "00 — Source Inventory", "\n".join(lines))


# ---------------------------------------------------------------- 01 project map
def project_map(model):
    L = ["Projects are identified from evidence, not directory names. Only `icarus` has an extraction.", ""]
    for p in C.PROJECTS:
        L += [f"## {p['name']} (`{p['id']}`)", "",
              f"- **Period:** {p['period']}", f"- **Evidence:** {p['evidence_level']}", f"- **Status:** {p['status']}",
              f"- **Purpose:** {p['purpose']}", f"- **Goals:** " + "; ".join(p["goals"]),
              f"- **Pivots:** " + ("; ".join(p["pivots"]) or "none recorded"),
              f"- **Technologies:** " + (", ".join(p["technologies"]) or "none recorded"),
              f"- **Major decisions:** " + (", ".join(f"[{d}]" for d in p["decisions"][:12]) + (" … (35 total, see 03)" if len(p["decisions"]) > 12 else "") or "none"),
              f"- **Lessons:** " + ", ".join(f"[{x}]" if x.startswith(("icarus:", "global:")) else x for x in p["lessons"]) if p["lessons"] else "- **Lessons:** none recorded",
              f"- **Relationship to trajectory:** {p['trajectory']}",
              f"- **Unresolved:** " + ", ".join(f"[{x}]" if x.startswith(("icarus:", "global:")) else x for x in p["unresolved"]),
              f"- **Evidence refs:** " + ", ".join(f"[{x}]" for x in p["refs"]), ""]
    L += ["## Mentioned but not extracted", "", "| name | what the corpus says | ref |", "|---|---|---|"]
    L += [f"| {n} | {d} | [{r}] |" for n, d, r in C.MENTIONED_PROJECTS]
    L += ["", "No claim in this compilation draws on these projects beyond the one line above.", "",
          "## Relationships (evidence-backed only)", "", "```text"]
    for a, rel, b, basis, note, refs in C.PROJECT_RELATIONS:
        L += [f"{a.upper()}", f"    ↓ {rel}   [{basis}] {note}  ({', '.join(refs)})", f"{b.upper()}", ""]
    L += ["```", "", "### Thematic links (compiler observation, NOT causal)", "",
          "- Pantheon.ai ('cited 13-artifact packet') and Icarus both centre on citations. No evidence that one influenced the other.",
          "- Signal and Icarus are both native macOS apps; Tempo and the Icarus site both show motion/visual craft. Same caveat.",
          "- Prior roles (agentic workflows, RAG content tools) precede Icarus's agent and retrieval work. Sequence only; no stated causation.",
          "", "## Within-Icarus phase chain (EXPLICIT, from 13_KNOWLEDGE_GRAPH.md)", "", "```text",
          "JARVIS v0 (local CLI, 'cannot bluff')", "    ↓ reset 2026-06-27 [icarus:D01]",
          "Phase 1 honest brain, headless", "    ↓ brain passed gates",
          "Phase 2 faces + private service", "    ↓ 'business phase begins' 07-16 [icarus:T17]",
          "Phase 3 depth / speaks-first", "    ↓ outreach failing; agents emerge as audience",
          "Phase 4 agent-facing brain + measurement era", "    ↓ launch pressure; distribution named the only blocker [icarus:B21]",
          "Current: launch, distribution, survival (to 2026-09-10)", "    ↓ ?", "[no evidence 2026-09-10 → 2026-10-03]", "```"]
    doc("01_PROJECT_MAP.md", "01 — Global Project Map", "\n".join(L))


# ---------------------------------------------------------------- 02 timeline
def timeline(model):
    eps = sorted(_of(model, "episode"), key=lambda r: (r.get("date") or "0000", r["line"]))
    L = ["All dates are 2026 unless stated. `date_raw` preserved. Sorted by normalized date; "
         "rows whose date is a claim or bound are labelled.", "",
         "## Chronology", "", "| date (raw) | event | why / consequence | ref |", "|---|---|---|---|"]
    for r in eps:
        L.append(f"| {r['date_raw']} | {_c(r['event'])} | {_c(r['why'])} | [{r['id']}] |")
    L += ["", "## Strands", ""]
    strands = {
        "Technical thinking": ["global:BT10", "global:BT11", "icarus:D02", "icarus:D12", "icarus:D13", "icarus:D27"],
        "Business thinking": ["icarus:D06", "global:BT05", "global:BT03", "icarus:D31", "global:GO08"],
        "Career direction": ["global:BT15", "icarus:FACT01L9", "icarus:FACT01L32"],
        "Beliefs that moved": ["global:BT01", "global:BT02", "global:BT07", "global:BT08", "global:BT09", "global:BT13"],
        "Major failures": ["icarus:F01", "icarus:F04", "icarus:F19", "icarus:F25", "icarus:F31", "icarus:F33", "icarus:F34"],
        "Major pivots": ["icarus:D01", "icarus:D06", "icarus:D11", "icarus:D30", "icarus:D31", "icarus:D33"],
    }
    from build_graph import _label
    for k, refs in strands.items():
        L += [f"### {k}", ""] + [f"- [{x}] {_c(_label(model, x))[:160]}" for x in refs] + [""]
    L += ["## State classification", "",
          "### Current state (latest evidence 2026-09-10)", "",
          "- Engineering core live: gate, ingest, public + private repos, Azure brain, Mac app 0.1.13, extension, Next.js site, MCP, terminal commands [icarus:X00L7]",
          "- Traction: zero paying customers, zero design partners, no pricing, no written ICP, '~10 users' self-reported [icarus:X00L9]",
          "- Active goals: 50 users (from 09-04); founder visibility (from 09-08) [icarus:D31]",
          "- Parallel job search (from 09-07) [icarus:FACT01L32]",
          "- Azure unaffordable; Oracle migration authorized, not run [icarus:D33]", "",
          "### Superseded state", "",
          "- Free models / public-only MVP [global:GB01]; per-user private storage [global:GB13]; three-channel rule [global:GB12]; "
          "4/4 tool-description claim [global:GB05]; analytics default-on [global:GB10]; hand-written site [global:GB11]; "
          "cold email and launch platforms as channels [global:GB03] [global:GB04]", "",
          "### Historical state", "",
          "- JARVIS v0 local CLI for 5–20 engineer companies [icarus:T01]; Render hosting [icarus:T12]; alpha tester program (alpha-1…6) [icarus:T15]", "",
          "### Uncertain state", "",
          "- Everything after 2026-09-10 [global:GO03]; March–June 2026 [global:GO05]; YC outcome [global:GO07]; barter outcome [icarus:O12]; "
          "whether ~10 users is real [icarus:C23]; founder vs job path [global:GO01]"]
    doc("02_GLOBAL_TIMELINE.md", "02 — Global Timeline", "\n".join(L))


# ---------------------------------------------------------------- 03 decisions
def decisions(model):
    L = ["35 decisions from the Icarus extraction, all PROJECT-SPECIFIC by default (see 14 for what generalizes). "
         "Fields not recorded in the source are shown as `—` rather than inferred.", "",
         "| ID | date | decision | status | outcome | reversal |", "|---|---|---|---|---|---|"]
    ds = sorted(_of(model, "decision"), key=lambda r: r["local_id"])
    for r in ds:
        L.append(f"| [{r['id']}] | {r['date_raw']} | {_c(r['title'])} | {r['global_status']} | {_c(r['outcome'])} | {r['later_reversal'] or '—'} |")
    L += ["", "## Detail", ""]
    for r in ds:
        f = r["fields"]
        L += [f"### [{r['id']}] {r['title']}", "",
              f"- **Date/period:** {r['date_raw']} · **Project:** icarus · **Confidence:** {r['confidence']}",
              f"- **Context / problem:** {f.get('context') or f.get('trigger') or f.get('_lead') or '—'}",
              f"- **Alternatives:** {f.get('options') or f.get('rejected') or '—'}",
              f"- **Chosen:** {f.get('chosen') or _c(r['title'])}",
              f"- **Rejected:** {f.get('rejected') or '—'}",
              f"- **Rationale:** {f.get('reason') or f.get('key') or '—'}",
              f"- **Evidence:** {f.get('evidence') or '—'}",
              f"- **Tradeoffs:** {f.get('tradeoff') or f.get('consequence') or '—'}",
              f"- **Outcome:** {r['outcome']}",
              f"- **Later reversal:** {r['later_reversal'] or 'none recorded'}",
              f"- **Status (source → global):** {f.get('status') or r['status_raw']} → **{r['global_status']}**",
              f"- **Source:** {f.get('source') or '—'} · compiled from {_src(r)}", ""]
    L += ["## Recurring decision patterns", "",
          "Persistence rule: a pattern is called PERSISTENT only with cross-project evidence. None qualifies: the corpus holds one project. "
          "Patterns below are labelled by their actual spread.", ""]
    for d in C.DECISION_PATTERNS:
        L += [f"### [global:{d['id']}] {d['pattern']}", "",
              f"- Spread: **{d['persistence']}** · domains: {', '.join(d['domains'])}",
              f"- Evidence: " + ", ".join(f"[{x}]" for x in d["evidence"]), ""]
    doc("03_GLOBAL_DECISION_REGISTER.md", "03 — Global Decision Register", "\n".join(L))


# ---------------------------------------------------------------- 04 beliefs
def beliefs(model):
    src = sorted(_of(model, "belief", prefix="icarus:"), key=lambda r: int(r["local_id"][1:]))
    hist = _of(model, "belief", prefix="global:")
    from collections import Counter
    cnt = Counter(r["global_status"] for r in src + hist)
    L = ["Statuses: CURRENT · PERSISTENT (spans project generations) · EVOLVING · HISTORICAL · REJECTED · EXPLORATORY · UNCERTAIN. "
         "Exploratory thinking is never promoted. 'first/last observed' are dates of evidence, not of the belief's birth.", "",
         "Status counts: " + ", ".join(f"{k} {v}" for k, v in sorted(cnt.items())), ""]
    domain = None
    for r in src:
        if r["domain"] != domain:
            domain = r["domain"]
            L += [f"## {domain}", ""]
        L += [f"### [{r['id']}] {r['statement']}", "",
              f"- **Status:** {r['global_status']} · **Confidence:** {r['confidence']} · **Kind:** {r['kind']} · **Class:** {r['classification']}",
              f"- **First / last observed:** {r['first_observed']} → {r['last_observed']}",
              f"- **Projects:** {', '.join(r['observed_in_projects'])}",
              f"- **Supporting evidence (source):** {r['text']}",
              f"- **Contradicting evidence:** {'; '.join(r['contradicting_evidence']) or 'none recorded'}",
              f"- **Associated decisions:** {', '.join(f'[{d}]' for d in r['associated_decisions']) or '—'}"]
        if r.get("compiler_note"):
            L.append(f"- **Compiler note:** {r['compiler_note']}")
        L += [f"- **Source:** {_src(r)}", ""]
    L += ["## Historical and rejected beliefs (reconstructed from decisions and reversals)", "",
          "These were not listed as beliefs by the extractor; they are inferred from decisions that were later reversed. Basis: RECONSTRUCTED, confidence MEDIUM.", "",
          "| ID | belief | status | held | evidence | what replaced it |", "|---|---|---|---|---|---|"]
    for r in sorted(hist, key=lambda r: r["id"]):
        L.append(f"| [{r['id']}] | {r['statement']} | {r['global_status']} | {r['first_observed']} → {r['last_observed']} | "
                 f"{', '.join(f'[{x}]' for x in r['refs'])} | {r['compiler_note']} |")
    doc("04_GLOBAL_BELIEF_SYSTEM.md", "04 — Global Belief System", "\n".join(L))


# ---------------------------------------------------------------- 05 evolution
def evolution(model):
    L = [f"{len(C.TRANSITIONS)} material belief transitions. Both sides are kept. A changed mind is context, not noise.", ""]
    for t in C.TRANSITIONS:
        L += [f"## [global:{t['id']}] {t['topic']}", "", "```text",
              f"EARLIER POSITION     {t['earlier']}", "        ↓",
              f"OBSERVATION          {t['observation']}", "        ↓",
              f"RECONSIDERATION      {t['reconsideration']}", "        ↓",
              f"NEW POSITION         {t['new']}", "        ↓",
              f"CURRENT STATUS       {t['status']}", "```", "",
              "Evidence: " + ", ".join(f"[{x}]" for x in t["refs"]), ""]
    L += ["## Beliefs that did NOT change (stability is also evidence)", "",
          "- [icarus:B01] 'must not bluff': unchanged from JARVIS v0 to 2026-09-10. The only belief spanning two project generations.",
          "- [icarus:B04] deterministic code for trust-bearing logic: from day-one gate to the end of the record.",
          "- [icarus:B20] files are memory: constant, even while specific docs drifted [global:GC07].", "",
          "## Pattern across transitions (INFERRED)", "",
          "- Engineering beliefs changed by **measurement** (BT08–BT11). Distribution beliefs changed by **zero results** (BT06, GB03, GB04) "
          "without instrumented comparison. Value beliefs changed by **deliberate choice against data** (BT07).",
          "- Cost and cash pressure drove the infrastructure transitions (BT01 start, BT12), not technical preference."]
    doc("05_BELIEF_EVOLUTION.md", "05 — Belief Evolution", "\n".join(L))


# ---------------------------------------------------------------- 10 failures
def failures(model):
    fs = sorted(_of(model, "failure"), key=lambda r: r["local_id"])
    L = ["Merged failure database. 'Changed later behavior' is judged from follow-up actions recorded in the source; "
         "UNKNOWN where none is recorded.", ""]
    cat = None
    for r in fs:
        if r["category"] != cat:
            cat = r["category"]
            L += [f"## {cat}", "", "| ID | what happened | why / lesson (source) | changed later behavior | recurring lesson |", "|---|---|---|---|---|"]
        L.append(f"| [{r['id']}] | {_c(r['title'])} | {_c(r['text'])} | {r.get('changed_later_behavior', 'UNKNOWN')} | "
                 f"{' '.join(f'[{x}]' for x in r.get('recurring_lessons', [])) or '—'} |")
    L += ["", "## Abandoned / not built", ""] + [f"- [{r['id']}] {r['text']}" for r in _of(model, "abandoned")]
    L += ["", "## His own lesson statements", ""] + [f"- [{r['id']}] {r['text']}" for r in _of(model, "lesson")]
    L += ["", "## Recurring lessons (across failures)", "",
          "Recurring = the same lesson extracted from ≥2 distinct failures. Single-instance lessons are listed but marked.", ""]
    for rl in C.RECURRING_LESSONS:
        L += [f"### [global:{rl['id']}] {rl['lesson']}", "",
              f"- Failures: " + ", ".join(f"[icarus:{f}]" for f in rl["failures"]) + f" ({len(rl['failures'])})",
              f"- Changed later behavior: {rl['changed']}", f"- Where it reappeared: {rl['reappeared']}",
              f"- Refs: " + ", ".join(f"[{x}]" for x in rl["refs"]), ""]
    L += ["## Most valuable signal (INFERRED)", "",
          "The lessons recur because the failure classes recur: silent failure (RL02) and measurement blind spots (RL03) appear from July to September. "
          "His own line [icarus:L7] is the best summary: knowing a failure mode is not designing against it."]
    doc("10_FAILURES_AND_LESSONS.md", "10 — Global Failures and Lessons", "\n".join(L))


# ---------------------------------------------------------------- 11 open loops
def open_loops(model):
    g = _of(model, "open_loop", prefix="global:")
    s = sorted(_of(model, "open_loop", prefix="icarus:"), key=lambda r: int(r["local_id"][1:]))
    L = ["## Cross-cutting open loops (compiler level)", "",
         "| ID | question | first | most recent | projects | current understanding | why unresolved | importance | status |", "|---|---|---|---|---|---|---|---|---|"]
    for r in g:
        L.append(f"| [{r['id']}] | {r['q']} | {r['first']} | {r['last']} | {', '.join(r['projects'])} | {r['understanding']} | {r['why']} | {r['importance']} | {r['status']} |")
    L += ["", "## Project open loops (Icarus, as of 2026-09-10)", "",
          "First appearance is the date in the source where given; 'most recent' is 2026-09-10 for all (the end of the record).", "",
          "| ID | question | why it matters | current understanding | next step | status |", "|---|---|---|---|---|---|"]
    for r in s:
        L.append(f"| [{r['id']}] | {_c(r['question'])} | {_c(r['why'])} | {_c(r['understanding'])} | {_c(r['next_step'])} | {_c(r['status'])} |")
    L += ["", "## Questions that keep reappearing", "",
          "- **ICP and pricing** [icarus:O1] [icarus:O2]: flagged 07-16, blocks Antler [icarus:O24], investors, outreach targeting. Reappears in every phase after 07-16.",
          "- **Which channel converts** [icarus:O8]: reappears with each channel switch (GC04).",
          "- **Is the honesty promise contractually true** [icarus:O5] [icarus:C17]: the product's core claim rests on an unverified console setting.",
          "- **Does Agent Mode beat a good CLAUDE.md** [icarus:O4]: the kill-or-keep question for the newest product direction."]
    doc("11_OPEN_LOOPS.md", "11 — Open Loops Register", "\n".join(L))


# ---------------------------------------------------------------- 12 contradictions
def contradictions(model):
    L = ["Never silently reconciled. Each entry keeps both positions.", "", "## Compiler-level contradictions", ""]
    for r in model["conflicts"]["global"]:
        L += [f"### [{r['id']}] {r['kind']}", "", "```text",
              f"POSITION A        {r['a']}", f"POSITION B        {r['b']}",
              f"WHEN A APPEARED   {r['when_a']}", f"WHEN B APPEARED   {r['when_b']}",
              f"POSSIBLE EXPLAN.  {r['explanation']}", f"STATUS            {r['status']}", "```",
              "Evidence: " + ", ".join(f"[{x}]" for x in r["refs"]), ""]
    L += ["## Source contradictions (Icarus extraction)", "", "| ID | conflict | detail (earlier vs later, evidence) | status |", "|---|---|---|---|"]
    for r in sorted(model["conflicts"]["source"], key=lambda r: int(r["local_id"][1:])):
        L.append(f"| [{r['id']}] | {_c(r['title'])} | {_c(r['text'])} | {r['global_status']} |")
    L += ["", "## Automatic checks", "", "| record | check | detail |", "|---|---|---|"]
    for a in model["conflicts"]["auto"]:
        L.append(f"| [{a['id']}] | {a['check']} | {_c(a['detail'])} |")
    L += ["", "## Categories", "",
          "- Conflicting beliefs: [icarus:C7] [global:GC05]", "- Contradictory goals: [global:GC06]",
          "- Outdated documentation: [icarus:C1] [icarus:C3] [icarus:C4] [icarus:C8] [icarus:C18] [icarus:C19] [global:GC07]",
          "- Decisions inconsistent with stated principles: [icarus:C9] [global:GC02] [global:GC04] [global:GC08] [icarus:C16]",
          "- Historical/current conflicts: [icarus:C2] [icarus:C5] [icarus:C6] [icarus:C12] [icarus:C14] [icarus:C15]",
          "- Project-specific vs global: [global:GC09] (all 'recurring' patterns rest on one project)"]
    doc("12_CONTRADICTIONS.md", "12 — Contradiction Register", "\n".join(L))


# ---------------------------------------------------------------- 13 intellectual map
def intellectual_map(model):
    ints = sorted(_of(model, "interest"), key=lambda r: -r["frequency"])
    L = ["Frequency = number of source records (decisions, beliefs, failures, episodes, notes…) matching the topic's keywords. "
         "It measures how much of the record a topic occupies, not how much he cares. Keywords are in `compiler/curated.py`.", "",
         "| ID | topic | frequency | dated span | nature | trend / status | note |", "|---|---|---|---|---|---|---|"]
    for r in ints:
        L.append(f"| [{r['id']}] | {r['name']} | {r['frequency']} | {r['first_dated'] or '?'} → {r['last_dated'] or '?'} | {r['nature']} | {r['trend']} | {r['compiler_note']} |")
    L += ["", "Projects: all frequencies come from the Icarus extraction. Interests with evidence outside Icarus (mention-level only): "
          "IN03 (prior agentic role, Pantheon.ai), IN09 (Tempo), IN10 (Signal), IN15 (prior automation roles, Signal), IN01/IN04/IN14 (JARVIS v0).", "",
          "## Conceptual graph", "", "```text",
          "                 ┌──────────── IN14 JARVIS scene (voice, overlay) ── IN10 native macOS ── IN09 visual/motion taste",
          "                 │",
          "IN04 intent / org memory ◄── IN03 AI agents & failure modes ◄── IN15 automation (prior roles)",
          "        │                         │",
          "        ▼                         ▼",
          "IN01 AI honesty / grounding ◄── IN02 retrieval (instrumental)",
          "        │        │",
          "        │        └──► IN06 privacy / trust boundaries",
          "        ▼",
          "IN05 measurement discipline ──► (applied, unevenly) ──► IN07 distribution / GTM ◄── IN11 startup strategy",
          "                                                          │",
          "                                                          ▼",
          "                                                 IN08 writing voice / content",
          "",
          "IN12 infra cost / survival ──► IN13 career / employment   (Sept 2026 pressure axis)",
          "```", "",
          "## Reading the map (INFERRED)", "",
          "- **Intrinsic core** (predates Icarus, or kept despite cost): honesty/grounding, intent preservation, the JARVIS scene.",
          "- **Instrumental ring**: retrieval, privacy, infrastructure: pursued because the core needs them.",
          "- **Pressure axis** rising in September: distribution, cost, career. These grew because the core did not sell, not out of interest (no evidence of intrinsic interest in GTM).",
          "- **Decreasing**: hands-on engineering depth (commits 309 Jul → 206 Aug → 12 Sep to 09-10) [icarus:X00L8]."]
    doc("13_INTELLECTUAL_MAP.md", "13 — Intellectual Map", "\n".join(L))


# ---------------------------------------------------------------- 14 transferable
def transferable(model):
    buckets = {}
    for r in _of(model, "belief", prefix="icarus:"):
        buckets.setdefault(r["classification"], []).append((r["id"], r["statement"], f"belief, {r['global_status']}"))
    for r in _of(model, "belief", prefix="global:"):
        buckets.setdefault("PROJECT-SPECIFIC", []).append((r["id"], r["statement"], f"reconstructed belief, {r['global_status']}"))
    for r in _of(model, "decision"):
        buckets.setdefault("PROJECT-SPECIFIC", []).append((r["id"], r["title"], "decision"))
    head_map = {"Likely general to Alankrit": "PERSONAL PREFERENCE", "Reusable technical knowledge": "TECHNICAL KNOWLEDGE",
                "Reusable product lessons": "PRODUCT KNOWLEDGE", "Reusable GTM lessons": "BUSINESS KNOWLEDGE",
                "Failed approaches worth avoiding": "TECHNICAL KNOWLEDGE", "Decisions that constrain future projects (if continued)": "PROJECT-SPECIFIC",
                "Project-specific (do not generalize)": "PROJECT-SPECIFIC"}
    for r in _of(model, "transferable_insight"):
        cls = head_map.get(r["heading"], "UNCERTAIN")
        if r["text"].startswith(("Templated cold email",)):
            cls = "BUSINESS KNOWLEDGE"
        if r["text"].startswith(("Strong visual taste", "Distribution is his recurring")):
            cls = "UNCERTAIN"
        buckets.setdefault(cls, []).append((r["id"], r["text"], f"extractor: {r['heading']}"))
    for r in _of(model, "reasoning_pattern"):
        buckets.setdefault("STRATEGIC PRINCIPLE" if r["local_id"] in {"R2", "R3", "R4", "R8", "R9", "R10", "R13", "R16"} else "UNCERTAIN", []).append(
            (r["id"], r["pattern"], "reasoning pattern (single project)"))
    order = ["PERSONAL PREFERENCE", "STRATEGIC PRINCIPLE", "TECHNICAL KNOWLEDGE", "PRODUCT KNOWLEDGE", "BUSINESS KNOWLEDGE", "UNCERTAIN", "PROJECT-SPECIFIC"]
    desc = {"PERSONAL PREFERENCE": "Potentially stable preference. Evidence repeats across surfaces (code, content, outreach, agent instructions) but within one project.",
            "STRATEGIC PRINCIPLE": "Potentially general principle. Stated as general by him; tested in one project.",
            "TECHNICAL KNOWLEDGE": "Reusable technical knowledge, independent of who holds it.",
            "PRODUCT KNOWLEDGE": "Reusable product knowledge.", "BUSINESS KNOWLEDGE": "Reusable business/GTM knowledge (mostly small-n).",
            "UNCERTAIN": "Insufficient evidence to classify, or in tension with other evidence.",
            "PROJECT-SPECIFIC": "Only relevant to Icarus. Never convert these into personality traits."}
    L = ["Rule: a project decision is never promoted to a personal trait. Only items with evidence on several surfaces "
         "(engineering, content, outreach, job search, agent instructions) or across project generations are labelled PERSONAL PREFERENCE.", "",
         "Counts: " + ", ".join(f"{k} {len(buckets.get(k, []))}" for k in order), ""]
    for k in order:
        L += [f"## {k}", "", desc[k], "", "| ref | insight | basis |", "|---|---|---|"]
        L += [f"| [{i}] | {_c(t)} | {b} |" for i, t, b in buckets.get(k, [])]
        L.append("")
    L += ["## Classification cautions", "",
          "- 'Address him as Alankrit' and 'no em-dashes' come from the Icarus CLAUDE.md and project memories. The extractor rates them general (HIGH). "
          "The em-dash rule spans content, outreach and docs; the address rule is evidenced only in one CLAUDE.md. Treat the address rule as UNCERTAIN outside Icarus.",
          "- 'Cash-constrained' is a 2026 constraint, not a preference [icarus:X11L8].",
          "- 'The bottleneck is distribution' [icarus:B21] is a diagnosis of Icarus, not a trait."]
    model["transferable_buckets"] = {k: len(v) for k, v in buckets.items()}
    doc("14_TRANSFERABLE_CONTEXT.md", "14 — Transferable Context", "\n".join(L))


# ---------------------------------------------------------------- voice examples dir
def voice_examples(model):
    vs = sorted(_of(model, "voice_example"), key=lambda r: r["id"])
    cats = ["argument", "explanation", "reflection", "technical reasoning", "disagreement", "short-form", "long-form", "humor", "directness", "counter-example"]
    prov = {"POSTED": "posted publicly by him (X/LinkedIn), as quoted by the extractor",
            "HIS_FEEDBACK": "his own words in feedback to agents (memories/vault)",
            "HIS_RULE": "a rule or template he specified", "HIS_FRAMING": "his framing, recorded in vault/plans",
            "DOC_PHRASE": "phrasing in his vault/repo docs; authorship may be shared with AI agents working under his direction",
            "AI_HOUSE_STYLE": "written by AI agents under his direction; NOT his direct voice",
            "REJECTED": "a line he rejected as not his voice"}
    idx = ["# Voice Examples", "", HDR.format(date=COMPILE_DATE),
           "Structured references, not copies of source files. Each excerpt was verified to occur verbatim in the cited source file "
           "(`verified` in `memory/voice_examples.jsonl`).", "", "## Provenance classes", ""]
    idx += [f"- **{k}**: {v}" for k, v in prov.items()]
    idx += ["", "## By category", ""]
    for c in cats:
        items = [v for v in vs if c in v["categories"]]
        idx.append(f"- [{c}]({c.replace(' ', '_')}.md): {len(items)}" + (" — **no genuine evidence in corpus**" if not items else ""))
        body = [f"# Voice examples: {c}", "", HDR.format(date=COMPILE_DATE)]
        if not items:
            body.append({"long-form": "No long-form text by Alankrit is in the corpus. Substack exists (every title opens with 'Why'; section headers are "
                                      "declarative thesis sentences) but was not read by the extractor. Do not synthesize long-form voice from short lines.",
                         "explanation": "No examples."}.get(c, "No examples."))
        for v in items:
            s = v["source"]
            body += [f"## [{v['id']}]", "", f"> {v['excerpt']}", "",
                     f"- Source: project `icarus`, file `{s['file']}`, line {s['line']} · verified: {v['verified']}",
                     f"- Date: not recorded with the excerpt (corpus evidence spans 2026-06-27 → 2026-09-10)",
                     f"- Provenance: **{v['provenance']}** ({prov[v['provenance']]})",
                     f"- Categories: {', '.join(v['categories'])}", f"- Why it represents his voice: {v['why']}", ""]
        if c == "humor":
            body.append("Caveat: humor evidence is thin. The corpus shows flat self-deprecation and a 'slightly wry' commit house style; no jokes.")
        write_text(f"voice_examples/{c.replace(' ', '_')}.md", "\n".join(body) + "\n")
    write_text("voice_examples/README.md", "\n".join(idx) + "\n")


def copy_narrative():
    for name in NARRATIVE:
        src = COMPILER_DIR / "narrative" / name
        if src.exists():
            text = src.read_text(encoding="utf-8")
            write_text(name, text)


def synthesize(model):
    for fn in (inventory, project_map, timeline, decisions, beliefs, evolution, failures, open_loops,
               contradictions, intellectual_map, transferable, voice_examples):
        fn(model)
    copy_narrative()
    return model
