"""Render the global documents from merged extraction records. No judgment is added here.

Every table row is a record from an extraction, shown with its id so it can be traced to
`memory/*.jsonl` and from there to file:line or a session message.
"""
from __future__ import annotations

import re
from collections import Counter

from common import COMPILE_DATE, WORKSPACE, write_text

WORKSPACE_POLICY = WORKSPACE / "BRAND_AGENT_POLICY.md"

HDR = ("> Generated by `python compiler/run.py` on {d}. Rows are copied from each project's `memory/*.jsonl`; ids are `<project>:<ID>`. "
       "Authorship, status and confidence labels are the extraction's own.\n")


def c(x, n=400):
    s = re.sub(r"\s+", " ", str(x if x is not None else "")).replace("|", "/").strip()
    return s if len(s) <= n else s[: n - 1] + "…"


def doc(name, title, body):
    write_text(name, f"# {title}\n\n{HDR.format(d=COMPILE_DATE)}\n{body.rstrip()}\n")


def rows(model, kind, typ=None):
    return [r for r in model["merged"].get(kind, []) if typ is None or r.get("type") == typ]


def inventory(model, scan):
    L = [f"Source: `{scan['source_path']}` · {scan['file_count']} files · {scan['total_bytes']:,} bytes · scanned {scan['scanned_at'][:19]}Z", "",
         "| project | schema | complete | latest evidence | rows | problems |", "|---|---|---|---|---|---|"]
    for p in model["projects"]:
        n = sum(len(v) for v in p["rows"].values())
        L.append(f"| {p['slug']} | {next((x['schema'] for x in scan['projects'] if x['slug']==p['slug']), '?')} | {p['complete']} | "
                 f"{p['manifest'].get('latest_evidence_date')} | {n} | {c('; '.join(p['problems']) or 'none')} |")
    L += ["", f"Unassigned files (no manifest, so not merged): {len(scan['unassigned_files'])}"]
    L += [f"- `{f}`" for f in scan["unassigned_files"][:30]]
    L += ["", "These are leftovers from extractions that were stopped before finishing, or loose files. They are never merged."]
    st = model["stats"]
    L += ["", f"Rows merged: {st['rows_total']} · independent: {st['rows_independent']} · derived from Icarus: {st['rows_derived_from_icarus']} · "
              f"duplicate ids: {len(st['duplicates'])}", "", "Machine-readable: `source_manifest.json`."]
    doc("00_SOURCE_INVENTORY.md", "00 — Source Inventory", "\n".join(L))


def project_map(model):
    L = []
    for p in model["projects"]:
        m = p["manifest"]
        L += [f"## {p['name']} (`{p['slug']}`)", ""]
        if not p["complete"]:
            L += [f"**Incomplete, not merged:** {', '.join(p['problems'])}", ""]
            continue
        L += [f"- Evidence through: {m.get('latest_evidence_date')} · extracted {m.get('extraction_date')} · protocol: {c(m.get('extraction_protocol', ''), 120)}",
              f"- Records: " + ", ".join(f"{k} {len(v)}" for k, v in p["rows"].items() if v),
              f"- Read first: `{p['root']}/HANDOFF_TO_ALANKRIT_OS.md`",
              "- Coverage gaps: " + "; ".join(c(g, 140) for g in m.get("coverage_gaps", [])[:6]), ""]
    L += ["## Not yet extracted", "", "See `00_SOURCE_INVENTORY.md`. Projects with session history but no merged extraction: Job Application Context, "
          "Marketing Intelligence, Design Portfolio, Solar Forecasting, thought-engine, Personal Brand, Video Editor Workflow, Icarus V2, X Post CLI. "
          "File-only projects (Campus Fund, Pantheon.ai, alankrit.dev, etc.) were never extracted."]
    doc("01_PROJECT_MAP.md", "01 — Project Map", "\n".join(L))


def timeline(model):
    L = ["Per-project chronologies, exactly as extracted. Dates are 2026 unless stated; they are not re-sorted across projects because "
         "extractions use different date formats.", ""]
    for p in model["projects"]:
        if not p["complete"]:
            continue
        L += [f"## {p['slug']}", "", "| id | when | event | status |", "|---|---|---|---|"]
        for r in p["rows"]["episodes"]:
            L.append(f"| {r['id']} | {c(r.get('date_raw') or r.get('time_ist') or (r.get('date') or {}).get('observed'), 40)} | {c(r['content'], 300)} | {c(r.get('status'), 60)} |")
        L.append("")
    L += ["## Current state (authored, newer than the extractions)", "", model["current_state"]]
    doc("02_GLOBAL_TIMELINE.md", "02 — Global Timeline", "\n".join(L))


def decisions(model):
    L = ["| id | decision | decider | status | source |", "|---|---|---|---|---|"]
    for r in rows(model, "decisions"):
        L.append(f"| {r['id']} | {c(r['content'], 260)} | {c(r.get('decider'), 40)} | {c(r.get('status'), 60)} | {c(r.get('source'), 80)} |")
    L += ["", "Full context, alternatives and tradeoffs per decision are in each project's `02_DECISION_REGISTER.md`."]
    doc("03_GLOBAL_DECISION_REGISTER.md", "03 — Global Decision Register", "\n".join(L))


def beliefs(model):
    bs = rows(model, "beliefs", "belief")
    cnt = Counter(r.get("status") for r in bs)
    L = ["Status counts: " + ", ".join(f"{k} {v}" for k, v in cnt.most_common()), "",
         "| id | belief | explicit/inferred | status | conf | counterevidence |", "|---|---|---|---|---|---|"]
    for r in bs:
        L.append(f"| {r['id']} | {c(r['content'], 240)} | {c(r.get('explicit_or_inferred'), 30)} | {c(r.get('status'), 40)} | {r.get('confidence')} | {c(r.get('counterevidence'), 160)} |")
    doc("04_GLOBAL_BELIEF_SYSTEM.md", "04 — Global Belief System", "\n".join(L))


def evolution(model):
    ts = rows(model, "beliefs", "belief_transition")
    L = [f"{len(ts)} recorded belief transitions. Earlier and new positions are both kept in the chain.", ""]
    for r in ts:
        L += [f"## {r['id']} — {c(r['content'], 160)}", "", "```text", r.get("chain", ""), "```", f"Status: {c(r.get('status'), 200)}", ""]
    doc("05_BELIEF_EVOLUTION.md", "05 — Belief Evolution", "\n".join(L))


def failures(model):
    L = ["| id | what happened | why | learned | changed afterwards | owner |", "|---|---|---|---|---|---|"]
    for r in rows(model, "failures"):
        L.append(f"| {r['id']} | {c(r.get('what_happened') or r['content'], 220)} | {c(r.get('why'), 140)} | {c(r.get('learned'), 140)} | {c(r.get('changed_afterwards'), 120)} | {c(r.get('owner'), 40)} |")
    L += ["", "## Lessons", "", "| id | lesson | label | scope |", "|---|---|---|---|"]
    for r in rows(model, "lessons"):
        L.append(f"| {r['id']} | {c(r['content'], 260)} | {c(r.get('status'), 50)} | {c(r.get('scope'), 40)} |")
    doc("10_FAILURES_AND_LESSONS.md", "10 — Failures and Lessons", "\n".join(L))


def open_loops(model):
    L = ["| id | question | why it matters | status | next step |", "|---|---|---|---|---|"]
    for r in rows(model, "open_loops"):
        L.append(f"| {r['id']} | {c(r['content'], 200)} | {c(r.get('why_it_matters'), 140)} | {c(r.get('status'), 60)} | {c(r.get('next_step'), 120)} |")
    doc("11_OPEN_LOOPS.md", "11 — Open Loops", "\n".join(L))


def contradictions(model):
    cf = model["conflicts"]
    L = ["Never reconciled here. Each keeps both positions.", "", "## Recorded by the extractions", "",
         "| id | position A | position B | status |", "|---|---|---|---|"]
    for r in cf["recorded"]:
        L.append(f"| {r['id']} | {c(r.get('position_a'), 220)} | {c(r.get('position_b'), 220)} | {c(r.get('status'), 60)} |")
    L += ["", f"## Cross-project contradiction edges ({len(cf['cross_project'])})", ""]
    L += [f"- {e['id']}: {e['from']} --{e['rel']}--> {e['to']}" for e in cf["cross_project"]] or ["- none"]
    L += ["", f"## Staleness ({len(cf['stale'])})", ""]
    L += [f"- `{s['project']}`: latest evidence {s['latest_evidence']}, {s['gap_days']} days before compile. Anything 'current' there is at most that recent." for s in cf["stale"]] or ["- none"]
    L += ["", f"## Automatic flags ({len(cf['auto'])})", "", "| record | check | detail |", "|---|---|---|"]
    L += [f"| {a['id']} | {a['check']} | {c(a['detail'], 200)} |" for a in cf["auto"]]
    doc("12_CONTRADICTIONS.md", "12 — Contradictions", "\n".join(L))


def evidence_summary(model):
    st = model["stats"]
    L = ["Frequency is not importance, and one project's echo of another is not independent evidence. This table shows what is independent.", "",
         "| project | rows | derived from Icarus | independent |", "|---|---|---|---|"]
    for slug in st["projects_complete"]:
        rs = [r for r in model["by_id"].values() if r["_extraction"] == slug]
        d = sum(1 for r in rs if r.get("derived_from_icarus"))
        L.append(f"| {slug} | {len(rs)} | {d} | {len(rs) - d} |")
    L += ["", "## Beliefs another project echoes (two-project evidence)", ""]
    echoes = [r for r in rows(model, "beliefs", "belief") if r.get("cross_project_echo") and str(r["cross_project_echo"]).strip() not in {"—", "-", ""}]
    L += [f"- {r['id']} → {c(r['cross_project_echo'], 200)}" for r in echoes] or ["- none"]
    L += ["", "Only items listed here have evidence in more than one project. Everything else is single-project."]
    doc("13_EVIDENCE_AND_ECHOES.md", "13 — Evidence and Cross-Project Echoes", "\n".join(L))


def transferable(model):
    L = ["Each project classifies its own insights as personal preference, strategic principle, technical, product, business, project-specific or uncertain. "
         "The global compiler does not re-classify. Read them per project:", ""]
    for p in model["projects"]:
        if p["complete"]:
            L.append(f"- `{p['root']}/11_TRANSFERABLE_CONTEXT.md`")
    L += ["", "Rule: a project decision is never promoted to a personal trait. An item is a likely personal preference only if it is evidenced in "
          "more than one project (see `13_EVIDENCE_AND_ECHOES.md`) or repeated across many sessions."]
    doc("14_TRANSFERABLE_CONTEXT.md", "14 — Transferable Context", "\n".join(L))


def voice(model):
    from common import out_path
    vs = rows(model, "voice_examples")
    by = {}
    for v in vs:
        by.setdefault(v.get("category") or "uncategorized", []).append(v)
    idx = ["# Voice examples", "", HDR.format(d=COMPILE_DATE), "Author labels are the extraction's: ALANKRIT (he typed it), ASSISTANT (agent text), UNKNOWN. "
           "Only ALANKRIT examples are his own words.", "", f"Total {len(vs)}; by author: {dict(Counter(str(v.get('author')).split(' ')[0] for v in vs))}", ""]
    for cat, items in sorted(by.items()):
        fn = f"voice_examples/{cat}.md"
        body = [f"# Voice examples: {cat}", ""]
        for v in items:
            body += [f"## {v['id']}", "", f"> {v['content']}", "", f"- Author: **{v.get('author')}**", f"- Source: {v.get('source')}",
                     f"- Why: {v.get('why_representative')}", f"- Verified verbatim: {v.get('verified_verbatim')}", ""]
        write_text(fn, "\n".join(body))
        idx.append(f"- [{cat}]({cat}.md): {len(items)}")
    write_text("voice_examples/README.md", "\n".join(idx) + "\n")


def _demote(text):
    return re.sub(r"^(#+) ", lambda m: "#" + m.group(1) + " ", text, flags=re.M)


def _sections(text, wanted):
    parts = re.split(r"^## ", text, flags=re.M)
    out = [("## " + s) for s in parts[1:] if any(s.lower().startswith(w) for w in wanted)]
    return "\n".join(out)


def entry_docs(model):
    comp = [p for p in model["projects"] if p["complete"]]
    stale = "; ".join(f"{s['project']} evidence ends {s['latest_evidence']}" for s in model["conflicts"]["stale"]) or "none"
    head = ("Compiled {d} from {n} complete extraction(s): {names}. Incomplete/unmerged: {inc}. Staleness: {stale}.\n\n"
            "**Read this first.** Two sources are authoritative and never merged: (1) `compiler/current_state.md`, Alankrit's own latest statement; "
            "(2) each project's handoff below. If they differ, the newer dated statement from Alankrit wins, and the older one stays as history.\n").format(
        d=COMPILE_DATE, n=len(comp), names=", ".join(p["slug"] for p in comp),
        inc=", ".join(model["stats"]["projects_incomplete"]) or "none", stale=stale)
    cur = "## Current state (Alankrit's own latest statement)\n\n" + model["current_state"].split("\n", 3)[-1].strip() + "\n"
    full = [f"# ALANKRIT GLOBAL CONTEXT\n\n{head}\n{cur}"]
    def body(p):
        if p["manifest"].get("confidential"):
            return ("_Confidential extraction: its contents are internal to the organisation and are not reproduced here._\n\n"
                    "Known from Alankrit's own statement (`compiler/current_state.md`): he works in the Founders Office at this VC. "
                    "Rule: nothing about its work, notes, people or investors goes into any public draft without his say-so for that item. "
                    "Details are kept only in the local extraction.")
        return _demote(p["handoff"])

    for p in comp:
        full.append(f"\n---\n\n# Project: {p['name']} (`{p['slug']}`)\n\n{body(p)}")
    pol = (WORKSPACE_POLICY.read_text(encoding="utf-8") if WORKSPACE_POLICY.exists() else "")
    if pol:
        full.append("\n---\n\n" + _demote(pol))
    full.append("\n---\n\n## Known limits of this compilation\n\n- Only the projects listed above are included. Everything else about Alankrit is absent, not negative.\n"
                "- `alankrit-os` is derived evidence (its claims restate Icarus); do not count it twice.\n"
                "- Statuses and classifications come from the extractions; no human has reviewed them.\n")
    write_text("ALANKRIT_GLOBAL_CONTEXT.md", "".join(full))
    short = [f"# HANDOFF TO ALANKRIT OS (global)\n\n{head}\n{cur}"]
    for p in comp:
        if p["manifest"].get("confidential"):
            short.append(f"\n---\n\n## {p['name']}: what to remember\n\nConfidential. Nothing about it in public drafts without Alankrit's say-so. Details stay local.\n")
            continue
        s = _sections(p["handoff"], ["unresolved", "what future agents", "never assume", "what should future", "what should they never"])
        short.append(f"\n---\n\n## {p['name']}: what to remember\n\nFull handoff: `{p['root']}/HANDOFF_TO_ALANKRIT_OS.md`\n\n{_demote(s)}")
    if WORKSPACE_POLICY.exists():
        short.insert(1, "\n## Brand agent policy (read before doing anything public)\n\nFull text: `BRAND_AGENT_POLICY.md`. Draft and queue only; Alankrit posts. "
                    "Claude writes first drafts and he edits them on his command. Campus Fund stays private. Own failures only if funny and occasional. "
                    "No em-dashes, no geopolitics, no job framing. Milestone dates are a proposal until he confirms.\n")
    write_text("HANDOFF_TO_ALANKRIT_OS.md", "".join(short))


def synthesize(model, scan):
    inventory(model, scan)
    for fn in (project_map, timeline, decisions, beliefs, evolution, failures, open_loops, contradictions,
               evidence_summary, transferable, voice, entry_docs):
        fn(model)
    return model
